 
 ############################## 
 # Country definition for CXB # 
 ############################## 
  
 country = 
 {  tag                    = CXB 
 	ai_settings	= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes MOB6 = yes} }	
   regular_id             = CHI 
   intrinsic_gov_type     = paternal_autocrat 
   extra_tc               = 2 
   puppet                 = CHI 
   control = CHI
   
   # Resource Reserves 
energy                 = 360
metal                  = 180
rare_materials         = 90
   oil                    = 100 
   supplies               = 100 
   money                  = 50 
   capital                = 1283 # Golmud 
   manpower               = 31 
   dissent                = 40 
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 3 
     political_left    = 4 
     freedom           = 3 
     free_market       = 3 
     professional_army = 6 
     defense_lobby     = 10 
     interventionism   = 3 
    } 
	
   nationalprovinces      = {  1268 1256 1270 1271 1264 1263 1262 1272 1265 1266 1283 1284 1285 } 
   ownedprovinces         = {  1268 1256 1270 1271 1264 1263 1262 1272 1265 1266 1283 1284 1285  } 
   controlledprovinces    = {  1268 1256 1270 1271 1264 1263 1262 1272 1265 1266 1283 1284 1285  } 
   # ROTW Minor Tech '36 
   # Group E 1936 techs 
   # ###################### 
   # GW fighter 
   techapps               = {  
#Interwar Fighter  
4500 4510 4520 4530
#Interwar Armoured Car  
2860
#Light Field Artillery  
2290
#SW Tank 
7600 7610
#Great War Infantry Division  
1010 1020 1030 1040 1050 1060 1070 1080
#Interbellum Supply 
1910 1920 1930 1940 1950 1960
#1916 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 
#Early Agriculture
5700 

# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
 } 
 inventions = { 3000027 }
   diplomacy = 
   {  relation = {  tag = CHI value = 200 access = yes  } 
     relation = {  tag = CSX value = 200 access = yes  } 
     relation = {  tag = U67 value = 150  } 
     relation = {  tag = CGX value = 200  } 
     relation = {  tag = CYN value = 200  } 
     relation = {  tag = JAP value = -75  } 
     relation = {  tag = MAN value = -75  } 
     relation = {  tag = CHC value = -100  } 
    } 
   SpyInfo                = {  country = "CXB" NumberOfSpies = 2  } 
   headofstate            = {  type = 9 id = 610001  } 
   headofgovernment       = {  type = 9 id = 610002  } 
   foreignminister        = {  type = 9 id = 610003  } 
   armamentminister       = {  type = 9 id = 610004  } 
   ministerofsecurity     = {  type = 9 id = 610005  } 
   ministerofintelligence = {  type = 9 id = 610006  } 
   chiefofstaff           = {  type = 9 id = 610007  } 
   chiefofarmy            = {  type = 9 id = 610008  } 
   chiefofnavy            = {  type = 9 id = 610009  } 
   chiefofair             = {  type = 9 id = 610010  } 
   # ###### 
   # XIBEI SAN MA OOB 
   # ###### 
  
  } 
 