    ##############################
    # Country definition for ITA #
    ##############################
     
    #####################
    # Country main data #
    #####################
     
    country =
    {  tag                    = ITA
 	ai_settings	= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes MOB6 = yes} }
       manpower               = 500
       # Resource Reserves
       energy                 = 3600
       metal                  = 1800
       rare_materials         = 1000
       oil                    = 3000
       supplies               = 2000
       money                  = 100
       capital                = 419
       transports             = 130
       escorts                = 35
 
  diplomacy =
  { relation = { tag = AFG value = 50 }
    relation = { tag = ARG value = 30 }
    relation = { tag = AST value = -200 }
    relation = { tag = BEL value = -200 }
    relation = { tag = BHU value = -200 }
    relation = { tag = BUL value = 150 }
    relation = { tag = CAN value = -200 }
    relation = { tag = CHI value = 25 }
    relation = { tag = CHL value = 30 }
    relation =
    { tag        = CRO
      value      = 200
      access     = yes
      guaranteed = { day = 1 month = may year = 1941 }
    }
    relation = { tag = SLO value = 120 }
    relation = { tag = ENG value = -200 }
    relation = { tag = ETH value = -200 }
    relation = { tag = FIN value = 100 }
    relation = { tag = U01 value = -200 }
    relation =
    { tag        = GER
      value      = 200
      guaranteed = { day = 27 month = september year = 1940 }
    }
    relation = { tag = HOL value = -200 }
    relation =
    { tag        = HUN
      value      = 200
      guaranteed = { day = 20 month = november year = 1940 }
    }
    relation = { tag = IRQ value = -200 }
    relation =
    { tag        = JAP
      value      = 125
      guaranteed = { day = 27 month = september year = 1940 }
    }
    relation =
    { tag        = MTN
      value      = 200
      access     = yes
      guaranteed = { day = 1 month = may year = 1941 }
    }
    relation = { tag = NEP value = -200 }
    relation = { tag = NIC value = -200 }
    relation = { tag = NZL value = -200 }
    relation = { tag = OMN value = -200 }
    relation = { tag = POR value = 65 }
    relation =
    { tag        = ROM
      value      = 150
      guaranteed = { day = 20 month = november year = 1940 }
    }
    relation = { tag = SAF value = -200 }
    relation = { tag = SAU value = -25 }
    relation = { tag = SCH value = -25 }
    relation =
    { tag        = SPA
      value      = 50
      guaranteed = { day = 18 month = november year = 1940 }
    }
    relation = { tag = TUR value = 1 }
    relation = { tag = FRA value = 50 }
    relation = { tag = YEM value = -200 }
  }
       SpyInfo                = {  country = "ITA" NumberOfSpies = 9  }
       # Somaliland
         nationalprovinces      = {  430 431 425 422 424 421 420 416 423 415 414 419 410 412 411 393 408 396 398 407 401 400 434 350 343   
            403 406 402 413 417 435 432 405 404 390 94 399 429 378 379 87 394 395 418 426 427 428 433 91 }
            #367 90 371 429 378 379 #added
            #389 335 361 329 359 334 362 360 87 2509#removed
       
       ownedprovinces         = { 430  431  425 422 424 421 420 416 423 415 414 419 410 412 411 393 408 396 398 407 401 400 434 378 
                                  379     403 406 394 395 418 426 427 428 433   
	                          402 413 417 435 432 405 404  399
                                         350 343       
 
#750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777 #Libya 
359 362 361 360 334 329 #Albania 
349 #Ljubljana
367 368 369 371 372 373 374 375 376 380 381 # Greece 

#90  86  94 93 92 91	87 # Occupation of France			
		}
       controlledprovinces    = {  430  431  425  422  424  421  420  416  423  415  414  419  410  412  411  393  408  396  398  407  401  400  434  378 
                                  379                
                                    
             403 406  394 395 418 426 427 428 433 402 413 417 435 432 405 404  399
                    350 343           
			 
#750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777 #Libya    
359 362 361 360 334 329 #Albania  
349 #Ljubljana
367 368 369 371 372 373 374 375 376 380 381 # Greece                       
						 
#90  86  94 93 92 91	87 # Occupation of France						  
 }
		claimedprovinces =  {   740 741 742 744 745 746 747 748 749 #Tunisia (owned by Vichy)
                                750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777 #Libya
                                359 362 361 360 334 329 #Albania
								349 #Ljubljana
                                367 368 369 371 372 373 374 375 376 380 381 # Greece
								90  86  94 93 92 91	87 # Occupation of France
							} 

	# ITA 1944.12 techs
	# ######################
	techapps = {  
	
	# Manufacturing
	5810 5820 5050 5830 5060 5070 5130
	# Construction Engineering 
	5800 5080 5090 5100
	# Agriculture 
	5700 5710 5010 5020 5030
	# Computers
	5310 54010 54020 54030 5320
	# Cryptography
	5316 5326 5327 5350 5360
	# Radar
	5410
	# Oil Refining
	5190
	# Atomic Research
	5470 
	# Medicine
	5600 5610 5620 5630 5640
	# Exp. Rocket
	5560
	
	# Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110
	# Mountain Division
	1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 1260
	# Cavalry
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390
	# Motorized Infantry
	1396 1400
	# Naval Infantry
	1560 1570 1580 1590
	# Paratroopers
	1670
	# Engineers
	1830 1840 1850 1860 1870
	# Supply 
	1910 1920 1930 1940 1950 1960 1970 1980 1990 199130

	# Tanks 
	7600 7610 2620 2010 2630 2640 2646 2650 2030 2040 2050 2070
	# Armored Car 
	2860 2870 2880 2020 2150 
	# Artillery
	2290 2300 2310 2900 2910 2920 2930 2940 2320 2330
	# Anti-Tank Artillery
	2400 2410
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460 2470
	# Anti-Air Artillery
	2810 2820 2510 2520

	# Hospital System 
	14000 14010 14020 14030
	# Great War Land Doctrines (entente)
	6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
	# WWII Land Doctrines
	6560 6030 6120 6110 6130
	# Armored Division Formation
	6900

	# Light Cruiser 
	3110 3120 3130 3140 3150 3160 12010
	# Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470
	# Battlecruiser  
	3310 3320 3330
	# Heavy Cruiser 
	3210 3220 3230 3240 3250 3260
	# Destroyer 
	3010 3020 3030 3040 3050 3060 3070 12000
	# Submarine 
	3610 3620 3630 3640 3650 3660 3670
	# Light carrier 
	12100 12110
	# Carrier
	3510 3520 3530
	# Torpedo & ASW
	3720 3730 3736 3740 3750 3900
	# Troopships
	3810 3820

	# Naval Doctrines
	# Engagement Theories
	8010 8020 8030 8040 8050 8060 8070 8080
	# Amphibious Warfare
	82300
	# Logistic Support
	82500
	# Naval Interdiction
	8500 8510 8520 8550
	# Trade Interdiction Submarine
	8600 8610
	# Engagement Tactics - Fleet-in-Being column
	8900 8910 8920 8930 8940 8950 8960 8970
	# Naval Supremacy
	8100 8110 8120 8150 8160 8170 8200 8210
	# Carrier
	81650

	# Interceptor Fighter  
	4500 4510 4520 4530 4540 4550 4010 4020 4030 4060 4090 
	# Multirole fighter
	4300 4310 4320 4330 4340 4040
	# Escort fighter
	4050
	# Close Air Support
    4400 4170
	# Tactical Bomber 
	4600 4610 4620 4630 4120 4130 4140 4150
	# Strategic Bomber
	4800 4810 4820
	# Naval Bomber
	4700 4710 4190
	# Seaplanes
	4740 4750 4760 4770 4780 4790 4850 4860
	# CAG
	4900 4910 4920
	# Air Transport 
	4290 4250 4260

	# Air Doctrines
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 
	9040 9050 9060 9070 9090 9100 9110 9120 9130 9140 9190 9200 9210 9220 9230 9240
	}

	inventions = { 3000027 }
       policy =
       {  date              = {  year = 0 month = january day = 0  }
         democratic        = 2
         political_left    = 3
         freedom           = 3 #former value was 4
         free_market       = 7
         professional_army = 6
         defense_lobby     = 7
         interventionism   = 8 #former value was 6
        }
       headofstate            = {  type = 9 id = 25001  }
       headofgovernment       = {  type = 9 id = 25002  }
       foreignminister        = {  type = 9 id = 25003  }
       armamentminister       = {  type = 9 id = 25047  }
       ministerofsecurity     = {  type = 9 id = 25005  }
       ministerofintelligence = {  type = 9 id = 25086  }
       chiefofstaff           = {  type = 9 id = 25097  }
       chiefofarmy            = {  type = 9 id = 25110  }
       chiefofnavy            = {  type = 9 id = 25117  }
       chiefofair             = {  type = 9 id = 25126  }
      
       dormant_ministers      = {  25016 25195 25008 }
      
	     # ######################
       # ITA 1948 LAND OOB

       # SUPREME COMMAND
       landunit =
       {  id       = {  type = 23500 id = 1  }
         location = 419
         name     = "Superesercito"
         division =
         { id       = {  type = 23500 id = 2  }
           name     = "Comando Supremo"
           type     = hq
           model    = 3
           strength = 100
           extra    = anti_air
           brigade_model = 3
          }
         division =
         { id       = {  type = 23500 id = 46  }
           name     = "12a Divisione 'Sassari'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6  }
         location = 378
         name     = "Guarnigione di Leros"
         Division =
         {  id       = {  type = 23500 id = 25  }
           name     = "Guarnigione di Leros"
           type     = garrison
           model    = 5
           strength = 30  #the garrison was 5500 soldiers strong
          }
        }
       # ARMY GROUP WEST
       landunit =
       {  id       = {  type = 23500 id = 6924  }
         location = 407
         name     = "Gruppo d'Armate Ovest Riserve"
         division =
         { id       = {  type = 23500 id = 9  }
           name     = "16a Divisione 'Pistoia'"
           type     = motorized
           model    = 2
           strength = 30
          }
        }
       # 4th Army
       landunit =
       {  id       = {  type = 23500 id = 6930  }
         location = 408
         name     = "IV Armata"
         division =
         { id       = {  type = 23500 id = 2500  }
           name     = "4a Armata"
           type     = hq
           model    = 3
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 18  }
           name     = "3a Divisione 'Ravenna'"
           type     = infantry
           model    = 11
           strength = 60
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 16  }
           name     = "4a Divisione Alpina 'Cuneense'"
           type     = bergsjaeger
           model    = 11
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 8  }
           name     = "5a Divisione Alpina 'Pusteria'"
           type     = bergsjaeger
           model    = 11
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 60  }
         location = 396
         name     = "XV Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 62  }
           name     = "10a Divisione 'Piave'"
           type     = motorized
           model    = 2
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 11  }
           name     = "7a Divisione 'Lupi di Toscana'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 27  }
           name     = "58a Divisione 'Legnano'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 52  }
         location = 398
         name     = "XXII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 6929  }
           name     = "103a Divisione 'Rovigo'"
           type     = motorized
           model    = 2
           strength = 30
          }
         division =
         { id       = {  type = 23500 id = 54  }
           name     = "2a Divisione 'Emanuele Filiberto'"
           type     = cavalry
           model    = 11
           strength = 70
           extra    = light_armor_brigade
	   brigade_model = 6
          }
         division =
         { id       = {  type = 23500 id = 96  }
           name     = "48a Divisione 'Taro'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       # 6th Army
       landunit =
       {  id       = {  type = 23500 id = 97  }
         location = 432
         name     = "VI Armata"
         division =
         { id       = {  type = 23500 id = 38  }
           name     = "6a Armata"
           type     = hq
           model    = 3
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 13  }
           name     = "4a Divisione 'Livorno'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 76  }
         location = 431
         name     = "XII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 77  }
           name     = "28a Divisione 'Aosta'"
           type     = infantry
           model    = 11
           strength = 60
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 37  }
           name     = "26a Divisione 'Assietta'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
           extra    = artillery
           brigade_model = 9
          }
         division =
         { id       = {  type = 23500 id = 6947  }
           name     = "202a Divisione Costiera"
           type     = garrison
           model    = 5
           strength = 50
          }
         division =
         { id       = {  type = 23500 id = 6948  }
           name     = "207a Divisione Costiera"
           type     = garrison
           model    = 5
           strength = 50
          }
         division =
         { id       = {  type = 23500 id = 6949  }
           name     = "208a Divisione Costiera"
           type     = garrison
           model    = 5
           strength = 50
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 4500  }
         location = 432
         name     = "XVI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 78  }
           name     = "54a Divisione 'Napoli'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6950  }
           name     = "206a Divisione Costiera"
           type     = garrison
           model    = 5
           strength = 50
          }
         division =
         { id       = {  type = 23500 id = 6951  }
           name     = "213a Divisione Costiera"
           type     = garrison
           model    = 5
           strength = 50
          }
        }
       # 7th Army
       landunit =
       {  id       = {  type = 23500 id = 6956  }
         location = 422
         name     = "VII Armata"
         division =
         { id       = {  type = 23500 id = 98  }
           name     = "7a Armata"
           type     = hq
           model    = 3
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 6927  }
           name     = "104a Divisione 'Mantova'"
           type     = motorized
           model    = 2
           strength = 30
          }
         division =
         { id       = {  type = 23500 id = 6938  }
           name     = "152a Divisione 'Piceno'"
           type     = garrison
           model    = 5
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6952  }
         location = 421
         name     = "VII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 6917  }
           name     = "6a Divisione Alpina 'Alpi Graje'"
           type     = bergsjaeger
           model    = 11
           strength = 80
          }
         division =
         { id       = {  type = 23500 id = 6928  }
           name     = "105a Divisione 'Rovigo'"
           type     = motorized
           model    = 2
           strength = 30
          }
         division =
         { id       = {  type = 23500 id = 103  }
           name     = "21a Divisione 'Granatieri di Sardegna'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6954  }
           name     = "183a Divisione 'Ciclone'"
           type     = paratrooper
           model    = 11
           strength = 50
          }
         division =
         { id       = {  type = 23500 id = 6955  }
           name     = "Divisione CCNN 'M'"
           type     = light_armor
           model    = 3
           strength = 45
          }
         division =
         { id       = {  type = 23500 id = 61  }
           name     = "9a Divisione 'Pasubio'"
           type     = motorized
           model    = 1
           strength = 55
          }
        }
       # 8th Army
       landunit =
       {  id       = {  type = 23500 id = 6909  }
         location = 419
         name     = "VIII Armata"
         division =
         { id       = {  type = 23500 id = 74  }
           name     = "8a Armata"
           type     = hq
           model    = 3
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 28  }
           name     = "2a Divisione Alpina 'Tridentina'"
           type     = bergsjaeger
           model    = 11
           strength = 30
          }
         division =
         { id       = {  type = 23500 id = 87  }
           name     = "3a Divisione Alpina 'Julia'"
           type     = bergsjaeger
           model    = 11
           strength = 20
          }
         division =
         { id       = {  type = 23500 id = 6958  }
           name     = "135a Divisione 'Ariete II'"
           type     = cavalry
           model    = 12
           strength = 50
           extra    = light_armor_brigade
	   brigade_model = 6
          }
         division =
         { id       = {  type = 23500 id = 21  }
           name     = "5a Divisione 'Cosseria'"
           type     = infantry
           model    = 11
           strength = 55
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 36  }
           name     = "2a Divisione 'Sforzesca'"
           type     = infantry
           model    = 10
           strength = 50
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 55  }
           name     = "3a Divisione 'Principe Amedeo'"
           type     = cavalry
           model    = 12
           strength = 30
           extra    = light_armor_brigade
	   brigade_model = 7
          }
         division =
         { id       = {  type = 23500 id = 63  }
           name     = "52a Divisione 'Torino'"
           type     = motorized
           model    = 1
           strength = 50
           extra    = armored_car
           brigade_model = 3
          }
        }
      
       # 5th Army
       landunit =
       {  id       = {  type = 23500 id = 6922  }
         location = 419
         name     = "V Armata"
         division =
         { id       = {  type = 23500 id = 110  }
           name     = "5a Armata"
           type     = hq
           model    = 3
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 100  }
           name     = "20a Divisione 'Friuli'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 23  }
           name     = "44a Divisione 'Cremona'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
           extra    = medium_armor
           brigade_model = 2
          }
         division =
         { id       = {  type = 23500 id = 6959  }
           name     = "225a Divisione Costiera"
           type     = garrison
           model    = 5
           strength = 50
          }
         division =
         { id       = {  type = 23500 id = 6960  }
           name     = "226a Divisione Costiera"
           type     = garrison
           model    = 5
           strength = 50
          }
        }
       # SUPREME COMMAND "SARDINIA"
       landunit =
       {  id       = {  type = 23500 id = 20  }
         location = 434
         name     = "XIII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 80  }
           name     = "30a Divisione 'Sabauda'"
           type     = infantry
           model    = 11
           strength = 60
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 81  }
           name     = "31a Divisione 'Calabria'"
           type     = infantry
           model    = 11
           strength = 60
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 95  }
           name     = "47a Divisione 'Bari'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6961  }
           name     = "184a Divisione 'Nembo'"
           type     = paratrooper
           model    = 11
           strength = 60
          }
        }
       # ARMY GROUP EAST
       # SUPREME COMMAND "SLOVENIA"
       # 2nd Army
       landunit =
       {  id       = {  type = 23500 id = 6943  }
         location = 349
         name     = "II Armata"
         division =
         { id       = {  type = 23500 id = 39  }
           name     = "2a Armata"
           type     = hq
           model    = 3
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 53  }
           name     = "1a Divisione 'Eugenio di Savoia'"
           type     = cavalry
           model    = 12
           strength = 70
           extra    = light_armor_brigade
	   brigade_model = 7
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6904  }
         location = 350
         name     = "V Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 43  }
           name     = "13a Divisione 'Re'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6914  }
           name     = "153a Divisione 'Macerata'"
           type     = garrison
           model    = 5
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6912  }
           name     = "154a Divisione 'Murge'"
           type     = garrison
           model    = 5
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 45  }
         location = 350
         name     = "VI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 70  }
           name     = "18a Divisione 'Messina'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 67  }
           name     = "32a Divisione 'Marche'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 42  }
         location = 349
         name     = "XI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 44  }
           name     = "14a Divisione 'Isonzo'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 7  }
           name     = "22a Divisione 'Cacciatori delle Alpi'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 49  }
           name     = "57a Divisione 'Lombardia'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6915  }
         location = 343
         name     = "XVIII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 47  }
           name     = "15a Divisione 'Bergamo'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6916  }
           name     = "158a Divisione 'Zara'"
           type     = garrison
           model    = 5
           strength = 70
          }
        }
       # MONTENEGRO ARMY COMMAND
       landunit =
       {  id       = {  type = 23500 id = 82  }
         location = 332
         name     = "Comando Truppe d'Montenegro"
         division =
         { id       = {  type = 23500 id = 84  }
           name     = "19a Divisione 'Venezia'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 85  }
           name     = "23a Divisione 'Ferrara'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6913  }
           name     = "155a Divisione 'Emilia'"
           type     = garrison
           model    = 5
           strength = 70
          }
         division =
         { id       = {  type = 23500 id = 30  }
           name     = "1a Divisione Alpina 'Taurinese'"
           type     = bergsjaeger
           model    = 11
           strength = 80
          }
        }
       # 9th Army
       landunit =
       {  id       = {  type = 23500 id = 6962  }
         location = 359
         name     = "IX Armata"
         division =
         { id       = {  type = 23500 id = 1003  }
           name     = "9a Armata"
           type     = hq
           model    = 3
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 6964  }
           name     = "1a Divisione 'Albania'"
           type     = infantry
           model    = 11
           strength = 60
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6965  }
           name     = "2a Divisione 'Albania'"
           type     = infantry
           model    = 11
           strength = 60
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 99  }
         location = 359
         name     = "IV Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 68  }
           name     = "38a Divisione 'Puglie'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 73  }
           name     = "49a Divisione 'Parma'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6966  }
         location = 362
         name     = "XXV Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 101  }
           name     = "41a Divisione 'Firenze'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 86  }
           name     = "53a Divisione 'Arezzo'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       # SUPREME COMMAND "GREECE"
       # 11th Army
       landunit =
       {  id       = {  type = 23500 id = 123  }
         location = 375
         name     = "XI Armata"
         division =
         { id       = {  type = 23500 id = 1004  }
           name     = "11a Armata"
           type     = hq
           model    = 3
           strength = 60
          }
         division =
         { id       = {  type = 23500 id = 26  }
           name     = "11a Divisione 'Brennero'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 6918  }
           name     = "151a Divisione 'Perugia'"
           type     = garrison
           model    = 5
           strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 102  }
         location = 375
         name     = "III Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 33  }
           name     = "24a Divisione 'Pinerolo'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 15  }
           name     = "36a Divisione 'Forlì'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 93  }
         location = 376
         name     = "VIII Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 94  }
           name     = "29a Divisione 'Piemonte'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 34  }
           name     = "59a Divisione 'Cagliari'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 690  }
         location = 367
         name     = "XVI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 22  }
           name     = "37a Divisione 'Modena'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
         division =
         { id       = {  type = 23500 id = 71  }
           name     = "56a Divisione 'Casale'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6903  }
         location = 371
         name     = "XVI Corpo d'Armata"
         division =
         { id       = {  type = 23500 id = 14  }
           name     = "33a Divisione 'Acqui'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6905  }
         location = 381
         name     = "Comando Truppe delle Isole Italiane dell'Egeo"
         division =
         { id       = {  type = 23500 id = 19  }
           name     = "6a Divisione 'Cuneo'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 105  }
         location = 379
         name     = "Comando Truppe delle Isole Italiane dell'Egeo"
         division =
         { id       = {  type = 23500 id = 106  }
           name     = "50a Divisione 'Regina'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6901  }
         location = 380
         name     = "Comando Truppe delle Isole Italiane dell'Egeo"
         division =
         { id       = {  type = 23500 id = 104  }
           name     = "51a Divisione 'Siena'"
           type     = infantry
           model    = 11
           strength = 70
           max_strength = 70
           extra    = artillery
           brigade_model = 8
          }
        }
       landunit =
       {  id       = {  type = 23500 id = 6941 }
         location = 405
         name     = "159a Divisione"
         division =
         { id       = {  type = 23500 id = 6942  }
           name     = "159a Divisione 'Veneto'"
           type     = garrison
           model    = 5
           strength = 70
          }
        }

    ####################################################################
      
	# ROYAL ITALIAN NAVY
	navalunit = { 
		id = { type = 23500 id = 2000 } 
		name = "Regia Marina" 
		location = 422 
		base = 422 
		division = { 
			id = { type = 23500 id = 263 } 
			name = "RN Taranto" 
			type = light_cruiser 
			model = 1 
			} 
		division = { 
			id = { type = 23500 id = 265 } 
			name = "II Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 233 } 
			name = "III Squadriglia Cacciatorpediere" 
			type = destroyer 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 216 } 
			name = "IV Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 4 
			}
		division = { 
			id = { type = 23500 id = 234 } 
			name = "V Squadriglia Cacciatorpediere" 
			type = destroyer 
			model = 4 
			}  
		division = { 
			id = { type = 23500 id = 282 } 
			name = "Squadrone Giorgio Orsini" 
			type = transport 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 6023 } 
			name = "RN Leonardo Da Vinci" 
			type = battleship
			model = 8
			} 
		division = { 
			id = { type = 23500 id = 6024 } 
			name = "RN Francesco Caracciolo" 
			type = battleship
			model = 8 
			} 
		division = { 
			id = { type = 23500 id = 6025 } 
			name = "RN Cristoforo Colombo" 
			type = battleship
			model = 8 
			} 
		division = { 
			id = { type = 23500 id = 6026 } 
			name = "RN Marcantonio Colonna" 
			type = battleship
			model = 9
			} 
		division = { 
			id = { type = 23500 id = 6029 } 
			name = "RN Falco" 
            type          = carrier  
            model         = 3  
            extra         = CAG  
            brigade_model = 3  
			} 
		division = { 
			id = { type = 23500 id = 6031 } 
			name = "RN Europa" 
            type          = light_carrier 
            model         = 1
            extra         = light_cag 
            brigade_model = 3  
			} 
		division = { 
			id = { type = 23500 id = 6032 } 
			name = "RN Etna" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 23500 id = 3033 } 
			name = "RN Pisa" 
			type = heavy_cruiser 
			model = 4 
			}
	}
	
	# 1ST FLEET
	navalunit = { 
		id = { type = 23500 id = 200 } 
		name = "Prima Squadra" 
		location = 422 
		base = 422 
		division = { 
			id = { type = 23500 id = 2001 } 
			name = "RN Giulio Cesare" 
			type = battleship 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 2002 } 
			name = "RN Andrea Doria" 
			type = battleship 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 401 } 
			name = "RN Caio Duilio" 
			type = battleship 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 2320 } 
			name = "RN Vittorio Veneto" 
			type = battleship 
			model = 7 
			}
		division = { 
			id = { type = 23500 id = 2329 } 
			name = "RN Littorio" 
			type = battleship 
			model = 7 
			}
		division = { 
			id = { type = 23500 id = 403 } 
			name = "RN Roma" 
			type = battleship 
			model = 7 
			}
		division = { 
			id = { type = 23500 id = 205 } 
			name = "RN Giuseppe Miraglia" 
			type = escort_carrier 
			} 
		division = { 
			id = { type = 23500 id = 204 } 
			name = "RN Luigi Cadorna" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 23500 id = 2040 } 
			name = "RN Duca degli Abruzzi" 
			type = light_cruiser 
			model = 4 
			}
		division = { 
			id = { type = 23500 id = 2041 } 
			name = "RN Giuseppe Garibaldi" 
			type = light_cruiser 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 404 } 
			name = "RN Attilio Regolo" 
			type = light_cruiser 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 412 } 
			name = "RN Pompeo Magno" 
			type = light_cruiser 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 413 } 
			name = "RN Scipione Africano" 
			type = light_cruiser 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 270 } 
			name = "VII Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 206 } 
			name = "VIII Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 6 
			}
		division = { 
			id = { type = 23500 id = 2060 } 
			name = "IX Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 6 
			}
		division = { 
			id = { type = 23500 id = 269 } 
			name = "XIV Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			}
		division = { 
			id = { type = 23500 id = 294 } 
			name = "XV Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 293 } 
			name = "XVI Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 2720 } 
			name = "Squadrone Aspromonte" 
			type = transport 
			model = 2 
			}
		division = { 
			id = { type = 23500 id = 2721 } 
			name = "Squadrone Maria" 
			type = transport 
			model = 2 
			}
		}
	# 2TH FLEET
	navalunit = { 
		id = { type = 23500 id = 207 } 
		name = "Seconda Squadra" 
		location = 396 
		base = 396 
		division = { 
			id = { type = 23500 id = 210 } 
			name = "RN Bolzano" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 5
			} 
		division = { 
			id = { type = 23500 id = 267 } 
			name = "RN Gorizia" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 5
			} 
		division = { 
			id = { type = 23500 id = 212 } 
			name = "RN Duca d'Aosta" 
			type = light_cruiser 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 214 } 
			name = "RN Raimondo Montecuccoli" 
			type = light_cruiser 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 2140 } 
			name = "RN Eugenio di Savoia" 
			type = light_cruiser 
			model = 4 
			}
		division = { 
			id = { type = 13500 id = 306 } 
			name = "La Galissonnière" # owned by Italy until handed over to the Free French after the Italian Armistice
			type = light_cruiser 
			model = 4 
			}
		division = { 
			id = { type = 23500 id = 296 } 
			name = "X Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 23500 id = 222 } 
			name = "XI Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 23500 id = 228 } 
			name = "XII Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 23500 id = 2220 } 
			name = "XIII Squadriglia Cacciatorpediniere" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 23500 id = 272 } 
			name = "Squadrone Sagittario" 
			type = transport 
			model = 2 
			}
		} 
	# AEGEAN SEA NAVAL COMMAND
	navalunit = { 
		id = { type = 23500 id = 218 } 
		name = "Comando Navale Mar Egeo" 
		location = 378 
		base = 378 
		division = { 
			id = { type = 23500 id = 219 } 
			name = "LI Squadriglia Sommergibili" 
			type = submarine 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 220 } 
			name = "LII Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		}
	# SUBMARINE FLEET
	# 1st Submarine Group
	navalunit = { 
		id = { type = 23500 id = 238 } 
		name = "I Gruppo Sommergibili" 
		location = 396 
		base = 396 
		division = { 
			id = { type = 23500 id = 239 } 
			name = "XI Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 240 } 
			name = "XII Squadriglia Sommergibili" 
			type = submarine 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 241 } 
			name = "XIII Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 242 } 
			name = "XIV Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 243 } 
			name = "XV Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 244 } 
			name = "XVII Squadriglia Sommergibili" 
			type = submarine 
			model = 3 
			} 
		}
	# 2nd Submarine Group
	navalunit = { 
		id = { type = 23500 id = 245 } 
		name = "II Gruppo Sommergibili" 
		location = 421 
		base = 421 
		division = { 
			id = { type = 23500 id = 249 } 
			name = "XXI Squadriglia Sommergibili" 
			type = submarine 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 250 } 
			name = "XXII Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			} 
		}  
	# 3rd Submarine Group
	navalunit = { 
		id = { type = 23500 id = 2380 } 
		name = "III Gruppo Sommergibili" 
		location = 422 
		base = 422 
		division = { 
			id = { type = 23500 id = 2390 } 
			name = "XXXI Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			}  
		division = { 
			id = { type = 23500 id = 253 } 
			name = "XXXIII Squadriglia Sommergibili" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 23500 id = 251 } 
			name = "XXXIV Squadriglia Sommergibili" 
			type = submarine 
			model = 5 
			} 
		division = { 
			id = { type = 23500 id = 252 } 
			name = "XXXV Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		}
	# 4th Submarine Group
	navalunit = { 
		id = { type = 23500 id = 254 } 
		name = "IV Gruppo Sommergibili" 
		location = 422 
		base = 422 
		division = { 
			id = { type = 23500 id = 255 } 
			name = "XL Squadriglia Sommergibili" 
			type = submarine 
			model = 4 
			} 
		division = { 
			id = { type = 23500 id = 230 } 
			name = "XLI Squadra Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 288 } 
			name = "XLVI Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 257 } 
			name = "XLVII Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 258 } 
			name = "XLIX Squadriglia Sommergibili" 
			type = submarine 
			model = 3 
			} 
		}
	# 7th Submarine Group
	navalunit = { 
		id = { type = 23500 id = 229 } 
		name = "VII Gruppo Sommergibili" 
		location = 434 
		base = 434 
		division = { 
			id = { type = 23500 id = 260 } 
			name = "LXXI Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 261 } 
			name = "LXXII Squadriglia Sommergibili" 
			type = submarine 
			model = 2 
			} 
		}  
	navalunit = { 
		id = { type = 23500 id = 271 } 
		name = "I Squadra di Marina Trasporti" 
		location = 419 
		base = 421  
		division = { 
			id = { type = 23500 id = 273 } 
			name = "Squadrone Aventino" 
			type = transport 
			model = 2 
			}  
		division = { 
			id = { type = 23500 id = 292 } 
			name = "VI Squadriglia Torpediniere" 
			type = destroyer 
			model = 3 
			}
		} 
	navalunit = { 
		id = { type = 23500 id = 276 } 
		name = "II Squadra di Marina Trasporti" 
		location = 421 
		base = 421 
		division = { 
			id = { type = 23500 id = 277 } 
			name = "Squadrone Vallelunga" 
			type = transport 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 278 } 
			name = "Squadrone Asmara" 
			type = transport 
			model = 2 
			} 
		division = { 
			id = { type = 23500 id = 283 } 
			name = "Squadrone Tarquinia" 
			type = transport 
			model = 2 
			} 
		}         



    ####################################################################
    
  # 1ST AIR FLEET
  airunit =
  { location = 407
    base     = 407
    id       = { type = 23500 id = 300 }
    name     = "1a Squadra Aerea"
    division =
    { id       = { type = 23500 id = 301 }
      name     = "2a Divisione Caccia 'Borea'"
      strength = 100
      type     = interceptor
      model    = 8
    }
    division =
    { id       = { type = 23500 id = 302 }
      name     = "4a Divisione Bombardieri 'Drago"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
    division =
    { id       = { type = 23500 id = 303 }
      name     = "6a Divisione Bombardieri 'Falco"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
  }
  # 2ND AIR FLEET
  airunit =
  { location = 421
    base     = 421
    id       = { type = 23500 id = 304 }
    name     = "2a Squadra Aerea"
    division =
    { id       = { type = 23500 id = 305 }
      name     = "1a Divisione Caccia 'Aquila'"
      strength = 100
      type     = interceptor
      model    = 8
    }
    division =
    { id       = { type = 23500 id = 306 }
      name     = "3a Divisione Bombardieri 'Centauro'"
      strength = 100
      type     = naval_bomber
      model    = 3
    }
    division =
    { id       = { type = 23500 id = 307 }
      name     = "11a Brigata Bombardieri 'Nibbio'"
      strength = 40
      type     = naval_bomber
      model    = 3
    }
  }
  # 3RD AIR FLEET
  airunit =
  { location = 419
    base     = 419
    id       = { type = 23500 id = 308 }
    name     = "3a Squadra Aerea"
    division =
    { id       = { type = 23500 id = 309 }
      name     = "5a Divisione Bombardieri 'Eolo'"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 23500 id = 310 }
      name     = "8a Brigata Caccia 'Ibis'"
      strength = 40
      type     = multi_role
      model    = 6
    }
  }
  # 4TH TERRITORIAL AIR FORCE ZONE
  airunit =
  { location = 422
    base     = 422
    id       = { type = 23500 id = 311 }
    name     = "4a Zona Aerea Territoriale"
    division =
    { id       = { type = 23500 id = 312 }
      name     = "9a Divisione Bombardieri 'Leone'"
      strength = 100
      type     = tactical_bomber
      model    = 7
    }
  }
  # SARDINIA AVIATION COMMAND
  airunit =
  { location = 434
    base     = 434
    id       = { type = 23500 id = 313 }
    name     = "Comando Aviazione di Sardegna"
    division =
    { id       = { type = 23500 id = 314 }
      name     = "10a Divisione Caccia 'Marte'"
      strength = 100
      type     = interceptor
      model    = 8
    }
  }
  # ROYAL AIR FORCE
  airunit =
  { location = 419 
    base     = 419
    id       = {  type = 23500 id = 318  }
    name     = "Regia Aeronautica"
    division =
    { id       = {  type = 23500 id = 319  }
      name     = "Comando Servici Aerei Speciali"
      strength = 25
      type     = transport_plane
      model    = 2
    }
  }
}
	

