 
 ############################## 
 # Country definition for TRK # 
 ############################## 
  
 country = 
 {  tag                    = U59
 	ai_settings	= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes MOB6 = yes} }	

energy                 = 360
metal                  = 180
rare_materials         = 90
oil                    = 100 
supplies               = 100 
money                  = 50 
capital                = 1142
manpower               = 250
dissent                = 5
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 3 
     political_left    = 4 
     freedom           = 3 
     free_market       = 3 
     professional_army = 6 
     defense_lobby     = 10 
     interventionism   = 3 
    } 
	
   nationalprovinces      = {  1142 } 
   ownedprovinces         = {  1142 1143 1144 1145 1146 1147 } 
   controlledprovinces    = {  1142 1143 1144 1145 1146 1147 } 
   # ROTW Minor Tech '36 
   # Group E 1936 techs 
   # ###################### 
   # GW fighter 
   techapps               = {  
#Interwar Fighter  
4500 4510 4520 4530
#Interwar Armoured Car  
2860
#Light Field Artillery  
2290
#SW Tank 
7600 7610
#Great War Infantry Division  
1010 1020 1030 1040 1050 1060 1070 1080
#Interbellum Supply 
1910 1920 1930 1940 1950 1960
#1916 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 
#Early Agriculture
5700 

# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
 } 
 inventions = { 3000027 }
   diplomacy = { } 
   SpyInfo                = {  country = "U59" NumberOfSpies = 2  } 
   headofstate            = {  type = 9 id = 1110001 } 
   headofgovernment       = {  type = 9 id = 1110002 } 
   foreignminister        = {  type = 9 id = 1110003 } 
   armamentminister       = {  type = 9 id = 1110004 } 
   ministerofsecurity     = {  type = 9 id = 1110005 } 
   ministerofintelligence = {  type = 9 id = 1110006 } 
   chiefofstaff           = {  type = 9 id = 1110007 } 
   chiefofarmy            = {  type = 9 id = 1110008 } 
   chiefofnavy            = {  type = 9 id = 1110009 } 
   chiefofair             = {  type = 9 id = 1110010 } 
  
  } 
 