 ############################## 
 # Country definition for SOV # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = SOV 
	ai_settings	= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes MOB6 = yes MOB7 = yes MOB8 = yes } }
   regular_id             = RUS 
   intrinsic_gov_type     = leninist 
   #ground_def_eff         = 0.88
   capital                = 572 
   # Resource Reserves 
energy                 = 50000
metal                  = 50000
rare_materials         = 5000
   oil                    = 5000 
   supplies               = 5000 
   money                  = 100 
   manpower               = 2000
   transports             = 30 
   escorts                = 15 
    
  diplomacy =
  { relation = { tag = AFG value = -10 }
    relation = { tag = BRA value = -50 }
    relation = { tag = BUL value = -150 }
    relation = { tag = CHI value = -50 }
	relation = { tag = CHC value = 50 }
    relation = { tag = ENG value = 150 }
    relation = { tag = FIN value = -50 }
    relation = { tag = U01 value = 100 }
	relation = { tag = PRK value = 200 access = yes}
    relation = { tag = GER value = -200 }
    relation =
    { tag        = MON
      value      = 150
      guaranteed = { day = 8 month = april year = 1947 }
      access     = yes
    }
    relation = { tag = PER value = -20 }
    relation = { tag = ROM value = -150 }
    relation =
    { tag        = SIK
      value      = 125
      guaranteed = { day = 30 month = december year = 1947 }
	  access = yes
    }
    relation = { tag = SPA value = -100 }
    relation = { tag = TUR value = 20 }
    relation = { tag = URU value = -100 }
    relation = { tag = USA value = 175 }
  }

   SpyInfo                = {  country = "SOV" NumberOfSpies = 10  } 
    
   nationalprovinces      = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180     1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154    
                              1153 1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545 
                              568 615 625 564 621 588 584    1138 1139 583 1136 1135          
                                  1151 1130 1137 598 1132  1133        699 632 592  689 688 
                              542  686 681 543  547              706 702 704 703 709 708 710 701 696 695 694  691  692  
                              697  698 700 645  659  662 661 660 666 639 1134 665 669 658 668 637  641  640   667    
                                 684 663  693    655  642  651  650  656  638  578  683  682  679  571  680  678  677  676  548  556  
                              554  569  572  570  585  574      559  561  551  557  549  553  550  552  560  566  599  595  616  611  612  619  
                              620  626  622  624  623  627  628  613  617  608  609  600  596  607  597  601  586  581  587  582  579  657  654  604  
                              580  652  630  631  634  635  636  603  602  647  646  644  643  614  633  649  653  648        
                                  567   573  565  590  591  589  594  605  606  610  629  575  577  562  558  563  707  1185  
                               711 712 713 1149 1141  593 1542 
               714 576 555 705 618
         1126 1127 1128 1069 1070 1161 1170 1171 
             
           
          
		
  1119 # Tannu Tuva
  

  
  } 
				 						 
   ownedprovinces         = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180     1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154    1153 
                              1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545  
                                       1138 1139  1136 1135           
                                 1151 1130 1137  1132  1133            689 688 542  
                              686 681 543  547                      
                                       666  1134     706       667     
                              684                             680      676  548      
                                                    660                                     1185   
                                 1149 1141   
                   
         1126 1127 1128 1069 1070 1161 1170 1171                
		   
#Idel-Ural 
672 664 #Tatarstan 
690 1131 # Bashkortostan 
671 #Udmurt Republic
673 # Mari El
687 # Perm Krai



#Central Asia
#Kazakhstan
506 507 505 500 498 504 1114 1117 1118 1116 503 1110 1108 1113 1115 1111 502 499 1109 1112 501 
#Turkmenistan
1097 1098   
#KYG
1107 1106  
#UZB
1101 1102 1100 1103 1099
#TAD
1105 1104 	 

#1223 1221 1222 1226 1227 1224 1225 # North Korea
1542 #South Sahalin
1543 # Kurils

1280 # Occupied East Turkestan

1219 #Port Arthur

1119 # Tannu Tuva
  }  

   controlledprovinces    = {  1191  1193 1192 1196 1195 1190 1187 1188 1175 1174 1541 1189 1176 1180     1181 1182 1183 1184  
                              1194 1179 1178 1168 1177 1169 1164 1163 1162 1167  1166 1186     1165 1150 1154    1153 
                              1152 1145 1146 1147 1158 1156    1157 1144 1143 1129 1142 1140 1148 685 1155 544 546   545  
                                       1138 1139  1136 1135           
                                 1151 1130 1137  1132  1133            689 688 542  
                              686 681 543  547                      
                                       666  1134     706       667     
                              684                             680      676  548      
                                                    660                                     1185   
                                 1149 1141   
                   
         1126 1127 1128 1069 1070 1161 1170 1171  
		   
#Idel-Ural
672 664 #Tatarstan 
690 1131 # Bashkortostan 
671 #Udmurt Republic
673 # Mari El
687 # Perm Krai

#Central Asia
#Kazakhstan
506 507 505 500 498 504 1114 1117 1118 1116 503 1110 1108 1113 1115 1111 502 499 1109 1112 501 
#Turkmenistan
1097 1098   
#KYG
1107 1106  
#UZB
1101 1102 1100 1103 1099
#TAD
1105 1104 	           

#1223 1221 1222 1226 1227 1224 1225 # North Korea
1542 #South Sahalin
1543 # Kurils

1219 #Port Arthur

1119 # Tannu Tuva

1280 # Occupied East Turkestan
     }
   claimedprovinces    = { 

 #Claimed
 241 242 244 247 254 245 238 255 257 251 240 248 250 239 249 258 256 253 # Former Polish areas.
 # Estonia
 274 275 271 272 273
 # Latvia
 267 269 268 266 265
 # Lithuania
 259 263 260
 270 264 262
 #Karelia
 530 531 532 534 535 536 537 538 539 540 541 517 519 
   
   
 #Bessarabia
 300 302  303 304 305 306
   } 

   # Soviet Techs 1944.12
   # ################ 
	techapps = {

	# Manufacturing
	5810 5820 5830 5050 5060 5070 5130
	# Assembly Line
	5140 5160 5180
	# Construction Engineering 
	5800 5080 5090 5100
	# Computers & cryptografi
	5310 54010 54020 54030 5320 5316 5326 5327 5350 5360
	# Agriculture  
	5700 5710 5010 5020 5030
	# Radar
	5410 5416 5417
	# Oil Refining 
	5190 5200
	# Atomics
	5470 5480
	# Medicine
	5600 5610 5620 5630
	# Rocket
	5560
	# Specialised Equipment
	5920
	
	# Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110 1120
	# Mountain Division 
	1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 1260 1270
	# Marines
	1560 1570 1580 1590 1600 1610
	# Paratroopers
	1670
	# Motorized Inf
	1396 1400 1410
	# Cavalry
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390 1530
	# Mechanized Inf
	1470
	# Engineers
	1830 1840 1850 1860 1870
	# Supply 
	1910 1920 1930 1940 1950 1960 1970 1980 1990 199100 199130 199140

	# Early/Light Tank 
	7600 7610 2620 2010 2630 2640 2646 2650 2030 2040 2050 2100 2110
	# Medium Tank
	2070 2080 2090
	# Armoured Car  
	2860 2870 2880 2020 2150
	# Field Artillery 
	2290 2300 2310 2900 2910 2920 2930 2940 2320 2330 2340
	# Self-Propelled Artillery
	2220 2230 2240
	# Self-Propelled Rocket
	2980
	# Anti-tank Artillery
	2400 2410
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460
	# Anti-air Brig
	2810 2820 2510 2520 2530
	# Tank Destroyer
	2170 2180
	#Rocket Artillery
	2970
 
 	# Hospital System 
	14000 14010 14020 14030
	# Great War Land Doctrines (central powers)
	6500 6510 6530 6550 6590 6600 6620 6650 6670 6610 6680 6690 6700 6710 6910
	# Land Doctrines
	6570 6300 6900 6310 6320 6330 6340 6350 6370 6360

	# Light Cruiser 
	3110 3120 3130 3140 3150 3160 
	# Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470 3480
	# Battlecruiser  
	3310 3320 3330 3340
	# Heavy Cruiser 
	3210 3220 3230 3240 3250 3260 12020
	# Destroyer 
	3010 3020 3030 3040 3050 3060 3070 12000
	# Submarine 
	3610 3620 3630 3640 3650 3660 3670
	# Light Carrier
	12100 12110 12120 12130
	# Fleet Carrier
	3510
	# Torpedo & ASW 18
	3720 3730 3736 3740 3750 3760 3900 3910
	# Troopships
	3810 3820 3830

	# Naval Doctrines 
	# Theory
	8010 8020 8030 8040 8050 8060 8070 8080
	# Amphib
	82300
	# Logistics
	82500
	# Naval Interdiction
	8500 8510 8550 8560 8600 8610 8520
	# Indirect Approach
	81300 81310 81320 81330 81340 81350 81360
	# Naval Supremacy
	8100 8110 8120 8150 8160 8200 8210 8170

	# CAS
	4400 4170 4280 4450
	# Inteceptor  
	4500 4510 4520 4530 4540 4550 4010 4020 4030 4060
	# Tactical Bomber 
	4600 4610 4620 4630 4120 4130 4140
	# Multirole fighter
	4300 4310 4320 4330 4340 4040 4070 4100
	# Escort Fighter
	4050 4080
	# Strategic bomber
	4800 4810 4820 4220 4230
	# Navalbomber
	4700 4710 4190
	# Transports
	4290 4250
	# Seaplanes
	4740 4750 4760 4770 4780 4790 4850
	
	# Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 
	9010 9040 9050 9060 9070 9080 9090 9100 9110 9120 9130 9140 9150 9160 9170 9180 9190 9200 9210 9220 9230 9240
 	} 

inventions = { 3000027 }
   blueprints             = {   } 
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 1 
     political_left    = 10 
     freedom           = 1 
     free_market       = 1 
     professional_army = 8 
     defense_lobby     = 10 
     interventionism   = 10 
    } 
	peacetime_ic_mod       = 0.7
   headofstate            = {  type = 9 id = 4001  } 
   headofgovernment       = {  type = 9 id = 4002  }  
   foreignminister        = {  type = 9 id = 4034  } 
   armamentminister       = {  type = 9 id = 40771  } 
   ministerofsecurity     = {  type = 9 id = 40781  } 
   ministerofintelligence = {  type = 9 id = 40811  } 
   chiefofstaff           = {  type = 9 id = 4007  } 
   chiefofarmy            = {  type = 9 id = 40762  } 
   chiefofnavy            = {  type = 9 id = 30049  } 
   chiefofair             = {  type = 9 id = 30053  }
   dormant_ministers      = {  30003 30005 30007 30009 30006 30010 30026 30027 30032 30033 30048 30053  }
   dormant_leaders        = {  30050 30040 30042 30044 30085 30095 30097 30101 30108 30111 30127 30131 30135 30152 30156 30170 30175 30192 30194 30207
                               30217 30220 30229 30232 30243 30255 30267 30272 30315 30316 30338 30339 30403 30409 30416 30454 30472 30477 30484 30487
                               30498 30523 30543 30547 30550 30570 30571 30572 30602 30618 30654 30664 30673 30678 30701 30715 30716 30717 30718 30719
                               30721 30722 30723 30650 30437 30512 30007 30374 30238 30276 30681 30353 30687 30407 30697 30499 30004 30008 30028
                               30057 30059 30063 30081 30084 30090 30098 30100 30107 30120 30136 30172 30174 30186 30190 30191 30198 30199 30214 30215
                               30226 30242 30258 30263 30269 30275 30277 30296 30302 30324 30326 30345 30381 30391 30399 30401 30411 30419 30442 30445
                               30447 30491 30494 30509 30521 30548 30552 30576 30614 30658 30660 30720 30473 30778 30076 30216 30744 30266 30322 30463
                               30479 30538 30789 30313 30765 30767 30515 30776 30528 30758 30373 30564
                            }

#1948

   landunit = 
   {  id       = {  type = 10848 id =  1 } 
     name     = "Raboche-Krest'yanskaya Krasnaya Armiya" 
     location = 572 #Moscow 
     Division = 
     {  id       = {  type = 10848 id = 2  } 
       name     = "Generalnyi Shtab RKKA" 
       strength = 100
       type     = HQ
	   model    = 4
	   extra    = artillery
	   brigade_model    = 10	
	   } 
 } 
   landunit = 
   {  id       = {  type = 10848 id =  3 } 
     name     = "Leningradskyi Voennyi Okrug" 
     location = 542 #Leningrad 
     Division = 
     {  id       = {  type = 10848 id = 4  } 
       name     = "Leningradskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 2
	   }
     Division = 
     {  id       = {  type = 10848 id = 5  } 
       name     = "177-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
      }
     Division = 
     {  id       = {  type = 10848 id = 6  } 
       name     = "191-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
      }
     Division = 
     {  id       = {  type = 10848 id = 7  } 
       name     = "8-ya Minskaya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  14 } 
     name     = "1-i Mekhanizirovannyi Korpus" 
     location = 672
      Division = 
     {  id       = {  type = 10848 id = 1400  } 
       name     = "1-ya Tankovaya Diviziya" 
       strength = 65 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1401  } 
       name     = "3-ya Tankovaya Diviziya" 
       strength = 65 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1402  } 
       name     = "163-ya Motostrelkovaya Diviziya" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }

   landunit = 
   {  id       = {  type = 10848 id =  37 } 
     name     = "50-i Strelkovyi Korpus" 
     location = 531
     Division = 
     {  id       = {  type = 10848 id = 38  } 
       name     = "43-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 39  } 
       name     = "70-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 40  } 
       name     = "123-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1403 } 
     name     = "10-i Mekhanizirovannyi Korpus" 
     location = 531
      Division = 
     {  id       = {  type = 10848 id = 1404  } 
       name     = "21-ya Tankovaya Diviziya" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1405  } 
       name     = "24-ya Tankovaya Diviziya" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1406  } 
       name     = "198-ya Motostrelkovaya Diviziya" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }

   landunit = 
   {  id       = {  type = 10848 id =  21 } 
     name     = "14-ya Armiya" 
     location = 535
     Division = 
     {  id       = {  type = 10848 id = 22  } 
       name     = "14-ya Krivorozhskaya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
      }
     Division = 
     {  id       = {  type = 10848 id = 23  } 
       name     = "52-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }

   landunit = 
   {  id       = {  type = 10848 id =  1420 } 
     name     = "17-i Mekhanizirovannyi Korpus" 
     location = 681
      Division = 
     {  id       = {  type = 10848 id = 1421  } 
       name     = "27-ya Tankovaya Diviziya" 
       strength = 10 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1422  } 
       name     = "36-ya Tankovaya Diviziya" 
       strength = 10 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1423  } 
       name     = "209-ya Motostrelkovaya Diviziya" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1424 } 
     name     = "20-i Mekhanizirovannyi Korpus" 
     location = 676
      Division = 
     {  id       = {  type = 10848 id = 1425  } 
       name     = "26-ya Tankovaya Diviziya" 
       strength = 10 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1426  } 
       name     = "38-ya Tankovaya Diviziya" 
       strength = 10 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1427  } 
       name     = "210-ya Motostrelkovaya Diviziya" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  191 } 
     name     = "Zakavkazskyi Voennyi Okrug" 
     location = 709
     Division = 
     {  id       = {  type = 10848 id = 192  } 
       name     = "Zakavkazskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 193  } 
       name     = "63-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 11
      }
     Division = 
     {  id       = {  type = 10848 id = 194  } 
       name     = "76-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 11
      }
     Division = 
     {  id       = {  type = 10848 id = 195  } 
       name     = "77-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 11
      }
     Division = 
     {  id       = {  type = 10848 id = 196  } 
       name     = "4-ya Smolenskaya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 197  } 
       name     = "20-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 198  } 
       name     = "136-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 199  } 
       name     = "138-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 200  } 
       name     = "47-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 201  } 
       name     = "17-ya Gor'kovskaya Strelkovaya Diviziya" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 11
      }
      Division = 
     {  id       = {  type = 10848 id = 202  } 
       name     = "24-ya Kavaleriiskaya Diviziya" 
       strength = 60 
       type     = cavalry
	   model    = 11
	extra = light_armor_brigade
	brigade_model = 3
      }
     Division = 
     {  id       = {  type = 10848 id = 203  } 
       name     = "31-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
      }
     Division = 
     {  id       = {  type = 10848 id = 204  } 
       name     = "9-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 11
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1485 } 
     name     = "28-i Mekhanizirovannyi Korpus" 
     location = 713
      Division = 
     {  id       = {  type = 10848 id = 1486  } 
       name     = "6-ya Tankovaya Diviziya" 
       strength = 65 
       type     = light_armor
	   model    = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1487  } 
       name     = "54-ya Tankovaya Diviziya" 
       strength = 65 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1488  } 
       name     = "236-ya Motostrelkovaya Diviziya" 
       strength = 80 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  205 } 
     name     = "Arhangelskyi Voennyi Okrug" 
     location = 542
     Division = 
     {  id       = {  type = 10848 id = 206  } 
       name     = "Arhangelskyi Voennyi Okrug" 
       strength = 70 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 207  } 
       name     = "88-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 9
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 208  } 
       name     = "111-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  209 } 
     name     = "Moskovskyi Voennyi Okrug" 
     location = 572
     Division = 
     {  id       = {  type = 10848 id = 210  } 
       name     = "Moskovskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 1
	   }
     Division = 
     {  id       = {  type = 10848 id = 211  } 
       name     = "118-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 212  } 
       name     = "235-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1492 } 
     name     = "4-i Vozdushno-Desantnye Korpus" 
     location = 547
     Division = 
     {  id       = {  type = 10848 id = 1493  } 
       name     = "4-i Vozdushno-Desantnye Korpus" 
       strength = 50 
       type     = paratrooper 
	   model    = 0
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1494 } 
     name     = "5-i Vozdushno-Desantnye Korpus" 
     location = 667
     Division = 
     {  id       = {  type = 10848 id = 1495  } 
       name     = "5-i Vozdushno-Desantnye Korpus" 
       strength = 50 
       type     = paratrooper 
	   model    = 0
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  219 } 
     name     = "Orlovskyi Voennyi Okrug" 
     location = 542
     Division = 
     {  id       = {  type = 10848 id = 220  } 
       name     = "Orlovskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 1
	   }
     Division = 
     {  id       = {  type = 10848 id = 221  } 
       name     = "19-ya Voronezhskaya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 222  } 
       name     = "89-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
      }
     Division = 
     {  id       = {  type = 10848 id = 224  } 
       name     = "120-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 225  } 
       name     = "145-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 227  } 
       name     = "149-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 223  } 
       name     = "217-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 226  } 
       name     = "222-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  229 } 
     name     = "Sredneaziatskyi Voennyi Okrug" 
     location = 1103
     Division = 
     {  id       = {  type = 10848 id = 230  } 
       name     = "Sredneaziatskyi Voennyi Okrug" 
       strength = 70 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 232  } 
       name     = "238-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  233 } 
     name     = "58-i Strelkovyi Korpus" 
     location = 1105
     Division = 
     {  id       = {  type = 10848 id = 231  } 
       name     = "68-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = bergsjaeger 
	   model    = 11
      }
     Division = 
     {  id       = {  type = 10848 id = 234  } 
       name     = "83-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 235  } 
       name     = "194-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
  Division = #SAVO
     {  id       = {  type = 10848 id = 236  } 
       name     = "18-ya Turkmenskaya Kavaleriiskaya Diviziya" 
       strength = 60 
       type     = cavalry
	   model    = 9
     }
  Division = #SAVO
     {  id       = {  type = 10848 id = 237  } 
       name     = "20-ya Tadzhikskaya Kavaleriiskaya Diviziya" 
       strength = 60 
       type     = cavalry
	   model    = 9
     }
  Division = #SAVO
     {  id       = {  type = 10848 id = 238  } 
       name     = "21-ya Kavaleriiskaya Diviziya" 
       strength = 60 
       type     = cavalry
	   model    = 9
     }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1506 } 
     name     = "27-i Mekhanizirovannyi Korpus" 
     location = 1103
      Division = 
     {  id       = {  type = 10848 id = 1507  } 
       name     = "9-ya Tankovaya Diviziya" 
       strength = 40 
       type     = light_armor
	   model    = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1508  } 
       name     = "53-ya Tankovaya Diviziya" 
       strength = 40 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1509  } 
       name     = "221-ya Motostrelkovaya Diviziya" 
       strength = 50 
       type     = motorized
	   model    = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  242 } 
     name     = "Zabaikalskyi Voennyi Okrug" 
     location = 1162
     Division = 
     {  id       = {  type = 10848 id = 243  } 
       name     = "Zabaikalskyi Voennyi Okrug" 
       strength = 80 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 244  } 
       name     = "93-ya Vostochno-Sibir. Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  245 } 
     name     = "Zabaikalskyi Voennyi Okrug" 
     location = 1169
     Division = 
     {  id       = {  type = 10848 id = 246  } 
       name     = "114-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  239 } 
     name     = "12-i Strelkovyi Korpus" 
     location = 1167
     Division = 
     {  id       = {  type = 10848 id = 240  } 
       name     = "65-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 241  } 
       name     = "94-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      } 
 }
   landunit = 
   {  id       = {  type = 10848 id =  1510 } 
     name     = "17-ya Armiya" 
     location = 1162
      Division = 
     {  id       = {  type = 10848 id = 1511  } 
       name     = "57-ya Tankovaya Diviziya" 
       strength = 20 
       type     = light_armor
	   model    = 0
      }
      Division = 
     {  id       = {  type = 10848 id = 1512  } 
       name     = "61-ya Tankovaya Diviziya" 
       strength = 20 
       type     = light_armor
	   model    = 0 
      }
     Division = 
     {  id       = {  type = 10848 id = 1513  } 
       name     = "36-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 1514  } 
       name     = "57-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      } 
     Division = 
     {  id       = {  type = 10848 id = 1515  } 
       name     = "82-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      } 
 }
   landunit = 
   {  id       = {  type = 10848 id =  1516 } 
     name     = "45-i Strelkovyi Korpus" 
     location = 660
     Division = 
     {  id       = {  type = 10848 id = 250  } 
       name     = "187-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 251  } 
       name     = "227-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 252  } 
       name     = "232-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1517 } 
     name     = "67-i Strelkovyi Korpus" 
     location = 666
     Division = 
     {  id       = {  type = 10848 id = 253  } 
       name     = "102-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 254  } 
       name     = "132-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 255  } 
       name     = "151-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1537 } 
     name     = "Uralskyi Voennyi Okrug" 
     location = 1151
     Division = 
     {  id       = {  type = 10848 id = 1538  } 
       name     = "Uralskyi Voennyi Okrug" 
       strength = 60 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 0
	   }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1539 } 
     name     = "Sibirskyi Voennyi Okrug" 
     location = 1142
     Division = 
     {  id       = {  type = 10848 id = 1540  } 
       name     = "Sibirskyi Voennyi Okrug" 
       strength = 60 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 0
	   }
 }
   landunit = 
   {  id       = {  type = 10848 id =  296 } 
     name     = "Dalnevostochnyi Front" 
     location = 1191
     Division = 
     {  id       = {  type = 10848 id = 297  } 
       name     = "Dalnevostochnyi Front" 
       strength = 80 
       type     = HQ
	   model    = 4
	   extra    = anti_air
	   brigade_model = 0
	   }
     Division = 
     {  id       = {  type = 10848 id = 298  } 
       name     = "35-ya Sibirskaya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 299  } 
       name     = "66-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 300  } 
       name     = "78-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  301 } 
     name     = "Dalnevostochnyi Front" 
     location = 1191
     Division = 
     {  id       = {  type = 10848 id = 302  } 
       name     = "79-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 303  } 
       name     = "101-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = bergsjaeger 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  304 } 
     name     = "1-ya Armiya" 
     location = 1196
     Division = 
     {  id       = {  type = 10848 id = 305  } 
       name     = "26-ya Zlatoustovskaya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 306  } 
       name     = "21-ya Permskaya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 307  } 
       name     = "22-ya Krasnodarskaya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 308  } 
       name     = "39-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 309  } 
       name     = "59-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 9
	   extra    = artillery
	   brigade_model = 8
      }
      Division = 
     {  id       = {  type = 10848 id = 312  } 
       name     = "8-ya Dalnevostochnaya Kavaleriiskaya Diviziya" 
       strength = 60 
       type     = cavalry
	   model    = 11
	extra = light_armor_brigade
	brigade_model = 3
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  1541 } 
     name     = "30-i Mekhanizirovannyi Korpus" 
     location = 1196
      Division = 
     {  id       = {  type = 10848 id = 1542  } 
       name     = "58-ya Tankovaya Diviziya" 
       strength = 65 
       type     = light_armor
	   model    = 1
      }
      Division = 
     {  id       = {  type = 10848 id = 1543  } 
       name     = "69-ya Tankovaya Diviziya" 
       strength = 65 
       type     = light_armor
	   model    = 1 
      }
      Division = 
     {  id       = {  type = 10848 id = 1544  } 
       name     = "239-ya Motostrelkovaya Diviziya" 
       strength = 80 
       type     = motorized
	   model    = 1
       extra    = medium_armor
       brigade_model = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  313 } 
     name     = "2-ya Armiya" 
     location = 1175
     Division = 
     {  id       = {  type = 10848 id = 314  } 
       name     = "12-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 315  } 
       name     = "3-ya Tihookeanskaya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
	   extra    = artillery
	   brigade_model = 8
      }
 }
   landunit = 
   {  id       = {  type = 10848 id = 1545  } 
     name     = "18-i Sibirskyi Korpus" 
     location = 1168
      Division = 
     {  id       = {  type = 10848 id = 1546  } 
       name     = "59-ya Tankovaya Diviziya" 
       strength = 40 
       type     = light_armor
	   model    = 0 
      }
      Division = 
     {  id       = {  type = 10848 id = 1547  } 
       name     = "69-ya Motostrelkovaya Diviziya" 
       strength = 80 
       type     = motorized
	   model    = 1
       extra    = medium_armor
       brigade_model = 1 
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  316 } 
     name     = "15-ya Armiya" 
     location = 1183
     Division = 
     {  id       = {  type = 10848 id = 317  } 
       name     = "34-ya Srednevolzhskaya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 9
      }
 }
   landunit = 
   {  id       = {  type = 10848 id =  318 } 
     name     = "25-ya Armiya" 
     location = 1190
     Division = 
     {  id       = {  type = 10848 id = 319  } 
       name     = "92-ya Strelkovaya Diviziya" 
       strength = 80 
       type     = infantry 
	   model    = 11
	   extra    = artillery
	   brigade_model = 8
      }
     Division = 
     {  id       = {  type = 10848 id = 320  } 
       name     = "32-ya Saratovskaya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 321  } 
       name     = "40-ya Bogucharskaya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
     Division = 
     {  id       = {  type = 10848 id = 322  } 
       name     = "105-ya Strelkovaya Diviziya" 
       strength = 70 
       type     = infantry 
	   model    = 9
      }
 }

# Air OOB
#MVO
airunit = { 
	id = { type = 10848 id = 7004 } 
	name = "Dal'nii Vostok Vozdushnogo Komandovaniya" 
	location = 1191 # Vladivostok 
	base = 1191 # Vladivostok 

	division = { 
	id = { type = 10848 id = 7005 } 
		name = "29.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7006 } 
		name = "79.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7007 } 
		name = "31.TBABR" 
		strength = 50 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7008 } 
		name = "32.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7001 } 
		name = "34.LSHABR" 
		strength = 80 
		type = cas 
		model = 1 
			}
	division = { 
	id = { type = 10848 id = 7002 } 
		name = "69.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			} 
	division = { 
	id = { type = 10848 id = 7003 } 
		name = "70.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	}
airunit = { 
	id = { type = 10848 id = 7016 } 
	name = "Leningradskaya Vozdushnogo Komandovaniya" 
	location = 542 # Leningrad
	base = 542 # Leningrad 

	division = { 
	id = { type = 10848 id = 7017 } 
		name = "1.LBABR" 
		strength = 80 
		type = multi_role 
		model = 4 
			}
	division = { 
	id = { type = 10848 id = 7018 } 
		name = "2.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7019 } 
		name = "4.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7020 } 
		name = "5.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7010 } 
		name = "23.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7011 } 
		name = "24.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7012 } 
		name = "26.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7013 } 
		name = "40.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7014 } 
		name = "41.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7015 } 
		name = "3.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	}
airunit = { 
	id = { type = 10848 id = 7026 } 
	name = "Pribaltii'skii Front Vozdushnogo Komandovaniya" 
	location = 264 # Riga
	base = 264 # Riga 

	division = { 
	id = { type = 10848 id = 7027 } 
		name = "6.LBABR" 
		strength = 80 
		type = multi_role 
		model = 4 
			}
	division = { 
	id = { type = 10848 id = 7028 } 
		name = "7.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7029 } 
		name = "8.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7030 } 
		name = "39.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7022 } 
		name = "12.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7023 } 
		name = "13.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7024 } 
		name = "57.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7025 } 
		name = "62.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	}
airunit = { 
	id = { type = 10848 id = 7037 } 
	name = "Zapadnyi Front Vozdushnogo Komandovaniya" 
	location = 597 # Luban
	base = 597 # Luban 

	division = { 
	id = { type = 10848 id = 7038 } 
		name = "9.LBABR" 
		strength = 80 
		type = multi_role 
		model = 4 
			}
	division = { 
	id = { type = 10848 id = 7039 } 
		name = "10.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7040 } 
		name = "11.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7041 } 
		name = "25.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7032 } 
		name = "28.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7033 } 
		name = "31.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7034 } 
		name = "29.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	division = { 
	id = { type = 10848 id = 7035 } 
		name = "30.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	division = { 
	id = { type = 10848 id = 7036 } 
		name = "42.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	}
airunit = { 
	id = { type = 10848 id = 7048 } 
	name = "Yugo-Zapadnogo Fronta Vozdushnogo Komandovaniya" 
	location = 240 # Tarnopol
	base = 240 # Tarnopol

	division = { 
	id = { type = 10848 id = 7049 } 
		name = "14.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7050 } 
		name = "15.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7051 } 
		name = "16.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7052 } 
		name = "17.IABR" 
		strength = 80 
		type = interceptor 
		model = 7 
			}
	division = { 
	id = { type = 10848 id = 7043 } 
		name = "19.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7044 } 
		name = "32.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7045 } 
		name = "33.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7046 } 
		name = "37.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7047 } 
		name = "34.TBABR" 
		strength = 80 
		type = strategic_bomber 
		model = 2 
			}
	}
airunit = { 
	id = { type = 10848 id = 7068 } 
	name = "Moskva Vozdushnogo Komandovaniya" 
	location = 572 # Moscow 
	base = 572 # Moscow 

	division = { 
	id = { type = 10848 id = 7069 } 
		name = "36.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7070 } 
		name = "43.IABR" 
		strength = 80 
		type = interceptor 
		model = 8 
			}
	division = { 
	id = { type = 10848 id = 7071 } 
		name = "46./48.ABRON" 
		strength = 70 
		type = transport_plane 
		model = 1
			}
	division = { 
	id = { type = 10848 id = 7072 } 
		name = "49./50.ABRON" 
		strength = 70 
		type = transport_plane 
		model = 1
			}
	division = { 
	id = { type = 10848 id = 7064 } 
		name = "44.LBABR" 
		strength = 80 
		type = multi_role 
		model = 5 
			}
	division = { 
	id = { type = 10848 id = 7065 } 
		name = "47.LSHABR" 
		strength = 80 
		type = cas 
		model = 1 
			}
	division = { 
	id = { type = 10848 id = 7066 } 
		name = "55.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	division = { 
	id = { type = 10848 id = 7067 } 
		name = "52.TBABR" 
		strength = 80 
		type = tactical_bomber 
		model = 6 
			}
	}

# Naval OOB

	navalunit = { # Dushenov K.I.
		id = { type = 10848 id = 5400 } 
		name = "Severnaya Voennaya Flotiliya" 
		location = 535 
		base = 535 
		division = { 
			id = { type = 10848 id = 5401 } 
			name = "1. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 6009 } 
			name = "2. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5402 } 
			name = "1. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 6008 } 
			name = "2. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5153 } 
			name = "3. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		} 	
	navalunit = { # Galler L.M.
		id = { type = 10848 id = 5100 } 
		name = "Krasnoznamenny Baltijsky Flot" 
		location = 542 
		base = 542 
		division = { 
			id = { type = 10848 id = 5101 } 
			name = "Marat" 
			type = battleship 
			model = 2 
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 5102 } 
			name = "Oktyabrskaya Revolutsiya" 
			type = battleship 
			model = 2 
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 6000 } 
			name = "Kirov" 
			type = heavy_cruiser
			model = 5 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 8501 } 
			name = "Maxim Gorky" 
			type = heavy_cruiser
			model = 5 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 5103 } 
			name = "3. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5104 } 
			name = "4. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5206 } 
			name = "5. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5500 } 
			name = "10. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5501 } 
			name = "11. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5154 } 
			name = "4. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6003 } 
			name = "5. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5161 } 
			name = "6. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5162 } 
			name = "7. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5163 } 
			name = "8. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5171 } 
			name = "9. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5301 } 
			name = "10. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		}  						
	navalunit = { # Kozhanov I.K.
		id = { type = 10848 id = 5200 } 
		name = "Chernomorskiy Flot" 
		location = 641 
		base = 641 
		division = { 
			id = { type = 10848 id = 5201 } 
			name = "Parizhskaya Kommuna" 
			type = battleship 
			model = 2 
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
			brigade_model2 = 0
			extra3 = naval_fire_controll_l
			brigade_model3 = 0
			extra4 = naval_anti_air_l
			brigade_model4 = 0			
			} 
		division = { 
			id = { type = 10848 id = 5202 } 
			name = "Krasnyi Kavkaz" 
			type = heavy_cruiser 
			model = 2 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 5203 } 
			name = "Krasnyi Krym" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5204 } 
			name = "Komintern" 
			type = light_cruiser 
			model = 0 
			} 
		division = { 
			id = { type = 10848 id = 5205 } 
			name = "Chervona Ukraina" 
			type = light_cruiser 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 8500 } 
			name = "Voroshilov" 
			type = heavy_cruiser
			model = 5 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 8502 } 
			name = "Molotov" 
			type = heavy_cruiser
			model = 5 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 10848 id = 5207 } 
			name = "6. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5502 } 
			name = "7. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5503 } 
			name = "12. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5504 } 
			name = "13. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5302 } 
			name = "11. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 6011 } 
			name = "12. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5172 } 
			name = "13. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5173 } 
			name = "14. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 6012 } 
			name = "15. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		} 
	navalunit = { # Viktorov M.V.
		id = { type = 10848 id = 5515 } 
		name = "Tikhookeanskiy Flot" 
		location = 1191 
		base = 1191 
		division = { 
			id = { type = 10848 id = 6001 } 
			name = "8. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6015 } 
			name = "9. Divizion Esmintsev" 
			type = destroyer 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6013 } 
			name = "16. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6014 } 
			name = "17. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 5551 } 
			name = "18. Divizion Podlodok" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 10848 id = 5552 } 
			name = "19. Divizion Podlodok" 
			type = submarine 
			model = 2 
			}
		division = { 
			id = { type = 10848 id = 5351 } 
			name = "20. Divizion Podlodok" 
			type = submarine 
			model = 1 
			} 
		division = { 
			id = { type = 10848 id = 5352 } 
			name = "21. Divizion Podlodok" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 10848 id = 5353 } 
			name = "22. Divizion Podlodok" 
			type = submarine 
			model = 4 
			}
		division = { 
			id = { type = 10848 id = 6006 } 
			name = "23. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6007 } 
			name = "24. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6018 } 
			name = "25. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6019 } 
			name = "26. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}
		division = { 
			id = { type = 10848 id = 6010 } 
			name = "27. Divizion Podlodok" 
			type = submarine 
			model = 3 
			}  
		division = { 
			id = { type = 10848 id = 6021 } 
			name = "28. Divizion Podlodok" 
			type = submarine 
			model = 4 
			}  
		division = { 
			id = { type = 10848 id = 6022 } 
			name = "29. Divizion Podlodok" 
			type = submarine 
			model = 4 
			}  
		division = { 
			id = { type = 10848 id = 6023 } 
			name = "30. Divizion Podlodok" 
			type = submarine 
			model = 4 
			}  
		division = { 
			id = { type = 10848 id = 6024 } 
			name = "31. Divizion Podlodok" 
			type = submarine 
			model = 4 
			}  
		division = { 
			id = { type = 10848 id = 6025 } 
			name = "32. Divizion Podlodok" 
			type = submarine 
			model = 4 
			}  
		division = { 
			id = { type = 10848 id = 6026 } 
			name = "33. Divizion Podlodok" 
			type = submarine 
			model = 4 
			}  
		division = { 
			id = { type = 10848 id = 5514 } 
			name = "1. Transportnaya Flotiliya" 
			type = transport 
			model = 2 
			} 
		} 	
	
	# Starting Build Queue 
	division_development = {
		name  = "Kaganovich"
		type  = heavy_cruiser
		model = 5
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8503 }
		date  = { year = 1942 month = december day = 31 }
	}
	division_development = {
		name  = "Kalinin"
		type  = heavy_cruiser
		model = 5
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8504 }
		date  = { year = 1944 month = december day = 6 }
	}
	division_development = {
		name  = "Chapayev"
		type  = heavy_cruiser
		model = 6
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8505 }
		date  = { year = 1943 month = march day = 8 }
	}
	division_development = {
		name  = "Zheleznyakov"
		type  = heavy_cruiser
		model = 6
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8506 }
		date  = { year = 1943 month = march day = 30 }
	}
	division_development = {
		name  = "Kuybyshev"
		type  = heavy_cruiser
		model = 6
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8507 }
		date  = { year = 1943 month = february day = 28 }
	}
	division_development = {
		name  = "Chkalov"
		type  = heavy_cruiser
		model = 6
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8508 }
		date  = { year = 1943 month = february day = 28 }
	}
	division_development = {
		name  = "Frunze"
		type  = heavy_cruiser
		model = 6
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8509 }
		date  = { year = 1943 month = february day = 26 }
	}
	division_development = {
		name  = "Ordzhinikidze"
		type  = heavy_cruiser
		model = 6
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8510 }
		date  = { year = 1943 month = august day = 24 }
	}
	division_development = {
		name  = "Sverdlov"
		type  = heavy_cruiser
		model = 6
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.1
		id    = { type = 10848 id = 8511 }
		date  = { year = 1943 month = october day = 3 }
	}
	division_development = {
		name  = "Kronshtadt"
		type  = battlecruiser
		model = 3
		cost  = 0.1
		id    = { type = 10848 id = 8512 }
		date  = { year = 1945 month = may day = 6 }
	}
	division_development = {
		name  = "Sevastopol"
		type  = battlecruiser
		model = 3
		cost  = 0.1
		id    = { type = 10848 id = 8513 }
		date  = { year = 1945 month = april day = 21 }
	}
	division_development = {
		name  = "Sovyetskiy Soyuz"
		type  = battleship
		model = 8
		cost  = 0.1
		id    = { type = 10848 id = 8514 }
		date  = { year = 1945 month = august day = 11 }
	}
	division_development = {
		name  = "Sovyetskaya Ukraina"
		type  = battleship
		model = 8
		cost  = 0.1
		id    = { type = 10848 id = 8515 }
		date  = { year = 1945 month = october day = 12 }
	}
	division_development = {
		name  = "Sovyetskaya Rossiya"
		type  = battleship
		model = 8
		cost  = 0.1
		id    = { type = 10848 id = 8516 }
		date  = { year = 1946 month = september day = 3 }
	}

 }	

	