 
 ############################## 
 # Country definition for ENG # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = ENG 
ai_settings	= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes MOB6 = yes } }
   capital                = 29 
   
   manpower               = 750
   energy                 = 65000
   metal                  = 65000
   rare_materials         = 5000
   oil                    = 6000 
   supplies               = 6000 
   money                  = 100 
   transports             = 1671 
   escorts                = 250 

  diplomacy =
  { relation = { tag = AFG value = -75 }
    relation = { tag = ARG value = 20 }
	relation = { tag = JOR value = 75 access = yes }
    relation = { tag = AST value = 200 access = yes }
    relation = { tag = BEL value = 200 }
    relation = { tag = BHU value = 200 access = yes }
    relation = { tag = BUL value = -150 }
    relation = { tag = CAN value = 200 access = yes }
    relation = { tag = CHI value = 80 }
    relation = { tag = SLO value = -100 }
    relation = { tag = ETH value = 50 }
    relation = { tag = FIN value = -50 }
    relation = { tag = U01 value = 200 access = yes guaranteed = { day = 1 month = december year = 1947 } }
    relation = { tag = GER value = -200 }
	relation = { tag = FRA value = -50 }
    relation = { tag = GUA value = 50 }
    relation = { tag = HOL value = -100 }
    relation = { tag = HON value = 50 }
    relation = { tag = HUN value = -100 }
    relation = { tag = IRE value = 50 }
    relation = { tag = IRQ value = 100 access = yes }
    relation = { tag = ITA value = -200 }
    relation = { tag = MEX value = 50 }
    relation = { tag = NEP value = 200 access = yes }
    relation = { tag = NZL value = 200 access = yes }
    relation = { tag = OMN value = 150 access = yes }
    relation = { tag = PER value = 100 access = yes }
    relation = { tag = POR value = 75 guaranteed = { day = 1 month = december year = 1947 } }
    relation = { tag = ROM value = -100 }
    relation = { tag = SAF value = 200 access = yes }
    relation =
    { tag        = SAU
      value      = 100
      guaranteed = { day = 1 month = december year = 1947 }
    }
    relation =
    { tag        = SCH
      value      = 50
      guaranteed = { day = 1 month = december year = 1947 }
    }
    relation = { tag = SIA value = 70 }
    relation = { tag = SOV value = 100 }
    relation = { tag = SPA value = -75 }
    relation = { tag = SWE value = 20 }
    relation =
    { tag        = TUR
      value      = 50
      guaranteed = { day = 1 month = december year = 1947 }
    }
    relation = { tag = USA value = 200 }
    relation = { tag = VEN value = -10 }
    relation = { tag        = YEM
      value      = 150
      access     = yes     
    }
    relation = { tag = NIC value = 200 }
    relation = { tag = U05 value = 125  }
    relation = { tag = U02 value = 200 access = yes }
  } 
   SpyInfo                = {  country = "ENG" NumberOfSpies = 12  } 
    
  nationalprovinces      = {  29 9 5 4 6 7 12 11 10 36 35 13 14 15 18 17 16 24 25 28  
        19 26 27 20 23 22 21 8 }
		
  claimedprovinces = {  
   # Palestine
   1172 1011 1010 1008 1009 1013 
   # Kuweit
   1041
   # Hong Kong
   1371 
   }
   
   
   ownedprovinces         = {  
   
   #Great Britain
   29 9 5 4 6 7 12 11 10 36 35 13 14 15 18 17 16 24 25 28 19 26 27 20 23 22 21 8
   
     #British Empire 
	 429 348 1011 1010  387 388 1773 1760 1772 1774 1753 1754 1755 1771 1038 2086 1757 1770 1763 1764 1769 1758 2045 1998 1997 1782 1766 1759 900 874 979 964 937 952 955 956 
   939 929 940 941 930 931 803 804 813 814 805 832 811 812 843 841 842 848 844 807 810 806 808 809 932 859 860 871 869 870 866 867 933 861 
   863 864 997 849 850 851 938 993 896           1039 1510 1511   1509 1728 1729      
   1749 1746  1172 1008 1009   1053 1051 840 998 1611 877 1041 1013    1613 1614   845  852 
        839 865 862 936 934 935 954 953 868 2 815 816 817 834 835 836 837 838            
		#818 819 820 821 822 823 824 825 826 827 828 829 830 831 Ethiopia 

		
750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777 #Libya 
 1371 #Hong Kong
 1432 1435 1436 1437 1438 1624 1625 1626 1433 1434 #Malaya & Singapore 
 1588 1589  1593    1590 1591 1592 1682 1678 1679 1680 1750 1687 #Pacific
}
 
   controlledprovinces    = {   #Great Britain
   29 9 5 4 6 7 12 11 10 36 35 13 14 15 18 17 16 24 25 28 19 26 27 20 23 22 21 8
   
  #British Empire 
	 429 348 1011 1010  387 388 1773 1760 1772 1774 1753 1754 1755 1771 1038 2086 1757 1770 1763 1764 1769 1758 2045 1998 1997 1782 1766 1759 900 874 979 964 937 952 955 956 
   939 929 940 941 930 931 803 804 813 814 805 832 811 812 843 841 842 848 844 807 810 806 808 809 932 859 860 871 869 870 866 867 933 861 
   863 864 997 849 850 851 938 993 896           1039 1510 1511   1509 1728 1729      
   1749 1746  1172 1008 1009   1053 1051 840 998 1611 877 1041 1013    1613 1614   845  852 
        839 865 862 936 934 935 954 953 868 2 815 816 817 834 835 836 837 838            
		#818 819 820 821 822 823 824 825 826 827 828 829 830 831 Ethiopia
		
750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777 #Libya  
 1371 #Hong Kong
 1432 1435 1436 1437 1438 1624 1625 1626  1433 1434 #Malaya & Singapore
 1588 1589  1593    1590 1591 1592 1682 1678 1679 1680 1750 1687 # Pacific
		} 
						
	# Commonwealth Tech '44.12 
	# UK 1944.12 techs 
	# ###################### 
	techapps = { 
	# Manufacturing
	5810 5820 5050 5830 5060 5070 5130
	# Assembly Line
	5140 5160 5180
	# Construction Engineering 
	5800 5080 5090 5100
	# Computers
	5310 54010 54020 54030 5320 5330 5340
	# Cryptography
	5316 5326 5327 5350 5360 5370 5380 5390 5400
	# Agriculture
	5700 5710 5010 5020 5030
	# Oil Refining
	5190 5200 5210 5220 5230 5240
	# Radar
	5410 5416 5417 5420 5426 5430 5440
	# Atomic Research 
	5470 5480 5490 5500 5510
	# Rocket
	5560
	# Medicine
	5600 5610 5620 5630 5640
	# Custom Equipment - Desert
	5960 5970

	# Infantry
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110 1120
	# Mountain Division 
	1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 1260 1270
	# Marine Division
	1560 1570 1580 1590 1600 1610
	# Airborne Division
	1670 1680 1690
	# Motorised Inf
	1396 1400 1410
	# Mechanised Inf
	1470
	# Cavalry
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390 1530
	# Engineers
	1830 1840 1850 1860 1870
	# Supply/Logisitics/Repair
	1910 1920 1930 1940 1950 1960 1970 1980 1990 199100 199110 199130 199140

	# Armor 
	7600 7610 2620 2010 2630 2640 2646 2650 2030 2040 2050 2070 2080 2090 2100 2110 2120 2130
	# Armoured Car 
	2860 2870 2880 2020 2150 2160
	# Field Artillery 
	2290 2300 2310 2900 2910 2920 2930 2940 2320 2330 2340
	# SP Art
	2220 2230 2240
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460 2470 2480
	# Anti-Air Artillery Brigade 
	2810 2820 2510 2520 2530 22910 22920 22930
	# Anti-tank Artillery
	2400 2410 2420 2430 2970 2370
	# Tank Destroyer
	2170 2180 2850
	# SP Rocket Artillery
	2980 2260

	# Hospital System 
	14000 14010 14020 14030
	# WWI Land Doctrines - Entente line: eng fra ita usa bel hol jap 
	6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
	# WWII Land Doctrines
	6560 6030 6120 6110 6420 6130 6140 6150 6170 6200
	# Armored Division Formation
	6900

	# Light Cruiser 
	3110 3120 3130 3140 3150 3160 12010
	# Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470 3480
	# Battlecruiser
	3310 3320 3330 3340
	# Heavy Cruiser 
	3210 3220 3230 3240 3250 3260
	# Destroyer 
	3010 3020 3030 3040 3050 3060 3070 12000
	# Submarine 
	3610 3620 3630 3640 3650 3660 3670
	# Light Carrier 
	12100 12110 12120 12130 12140
	# Fleet Carrier 
	3510 3520 3530 3540 3550 12060
	# Torpedo & ASW 18
	3720 3730 3736 3740 3750 3760 3770 3900 3910 3920
	# Troopships
	3810 3820 3830 3840

	# Naval Doctrines
	# Theories
	8010 8020 8030 8040 8050 8060 8070 8080
	# Amphib
	82300 82310 82320 82330
	# Logistic Support
	82500 82510 82520
	# Naval Interdiction
	8500 8510 8520 8550 8560 8600 8610
	# Engagement Tactics
	8900 8910 8920 8930 8940 8950 8960 8970 8980
	# Naval Supremacy
	8100 8110 8120 8150 8160 8200 8210 8220 8230 8240 8170
	# Carrier Doctrine
	81650 
	# Carrier - Scouting Focus Line
	81850 81860 81870 81880 81890 81900 81910
	# Carrier - Strike Line
	81700 81710 81720 81730 81740 81750 81760
	
	# Interceptors
	4500 4510 4520 4530 4540 4550 4010 4020 4030 4060 4090 15000
	# Tactical Bombers
	4600 4610 4620 4630 4120 4130 4140 4150 4160
	# Close Air Support
	4400 4170 4280 4450
	# Escort Fighters
	4050 4080 4110
	# Multirole fighter
	4300 4310 4320 4330 4340 4040 4070 4100
	# Transports
	4290 4250 4260 4270
	# Naval bomber
	4700 4710 4190 4200
	# CAG 43
	4900 4910 4920 4930 4940 4950
	# Strategic Bomber 
	4800 4810 4820 4220 4230 4240
	# Seaplanes
	4740 4750 4760 4770 4780 4790 4850 4860

	#Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 
	9010 9040 9050 9060 9090 9140 9150 9160 9170 9180 9070 9080 9100 9110 9120 9130 9190 9200 9210 9220
        9230 9240 9250 9260 9270 9280 9290 9300 9310 9320 9330 9340 9350 9360 9370 9380 9390 9400 9410 9420
	9430 9440 9450 9460

	#rocket engine
	7550 7560 7570 15500
	} 

inventions = { 3000027 3000028 3000012 }
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 8 
     political_left    = 2 
     freedom           = 8 
     free_market       = 8 
     professional_army = 6 
     defense_lobby     = 7 
     interventionism   = 6 
    }
   headofstate            = {  type = 9 id = 10014  } 
   headofgovernment       = {  type = 9 id = 10018  } 
   foreignminister        = {  type = 9 id = 10003  } 
   armamentminister       = {  type = 9 id = 10038  } 
   ministerofsecurity     = {  type = 9 id = 10064  } 
   ministerofintelligence = {  type = 9 id = 10078  } 
   chiefofstaff           = {  type = 9 id = 10094  } 
   chiefofarmy            = {  type = 9 id = 10104  } 
   chiefofnavy            = {  type = 9 id = 10112  } 
   chiefofair             = {  type = 9 id = 10117  }
   dormant_ministers      = {  10001 10011 10002 10004 10005 10058 10006 10007 10008 10101 10102 10009 10109 10010 10017 10022 10091 10103 10105 10119 10059 10131 10141 10142 10093 
                               10112 10039 
                            }
   dormant_leaders        = {  10083 10313  }
  
   # ## United Kingdom Land OOB ### 
   landunit = 
   {  name     = "Aldershot Command" 
     location = 27 
     id       = {  type = 12700 id = 1  } 
     Division = 
     {  id       = {  type = 12700 id = 63  } 
       name     = "British Army HQ" 
       type     = hq 
       model    = 4 
       strength = 100
       experience = 30 
      }
     Division = 
     {  id            = {  type = 12700 id = 1902  } 
       name 	= "1st Airborne Division" 
       type     = paratrooper 
	   model    = 2
       strength = 20
       extra    = glider_artillery
       brigade_model = 1	   
       experience = 50
      } 
     Division = 
     {  id       = {  type = 12700 id = 1502  } 
       name     = "50th (Northumbrian) Division" 
       type     = infantry 
	   model    = 11
       strength = 90
       experience = 40
      }  
    } 
   landunit = 
   {  name     = "Southern Command" 
     location = 26 
     id       = {  type = 12700 id = 6  } 
     Division = 
     {  id       = {  type = 12700 id = 506  } 
       name     = "48th (South Midland) Division" 
       type     = infantry 
	   model    = 11
       strength = 100
       experience = 30 
      }
    } 
   landunit = 
   {  name     = "Western Command" 
     location = 17 
     id       = {  type = 12700 id = 514  } 
     Division = 
     {  id       = {  type = 12700 id = 517  } 
       name     = "55th (West Lancashire) Division" 
       type     = infantry 
	   model    = 11
       strength = 100
       experience = 30 
      }  
    } 
   landunit = 
   {  name     = "Eastern Command" 
     location = 25 
     id       = {  type = 12700 id = 521  } 
     Division = 
     {  id       = {  type = 12700 id = 508  } 
       name     = "61st (South Midland) Division" 
       type     = infantry 
	   model    = 11
       strength = 100
       experience = 30 
      }  
    } 
   landunit = 
   {  name     = "London District" 
     location = 29 
     id       = {  type = 12700 id = 527  } 
     Division = 
     {  id       = {  type = 12700 id = 528  } 
       name     = "47th (London) Division" 
       type     = motorized 
	   model    = 2
       strength = 100
       extra    = anti_air
       brigade_model = 4
       experience = 30 
      }  
    } 
   landunit = 
   {  name     = "XIII Corps" 
     location = 28 
     id       = {  type = 12700 id = 1000  } 
     Division = 
     {  id       = {  type = 12700 id = 5050  } 
       name     = "1st Armoured Div. (Royal Hussars)" 
       type     = armor 
	   model    = 2
       strength = 80
       experience = 50
      }   
     Division = 
     {  id       = {  type = 12700 id = 1920  } 
       name     = "6th Armoured Division" 
       type     = armor 
	   model    = 2
       strength = 70
       extra    = heavy_armor
       brigade_model = 1
       experience = 30
      } 
    } 
   landunit = 
   {  name     = "2nd Army" 
      leader   = 10078 # Dempsey
     location = 29 
     id       = {  type = 12700 id = 3805  } 
     Division = 
     {  id       = {  type = 12700 id = 3806  } 
       name     = "2nd Army" 
       type     = hq 
       model    = 4 
       strength = 100
       extra    = anti_air
       brigade_model = 4
       experience = 30
      }
     Division = 
     {  id            = {  type = 12700 id = 3800  } 
       name 	= "6th Airborne Division" 
       type     = paratrooper 
	   model    = 2
       strength = 80
       extra    = glider_artillery
       brigade_model = 1	   
       experience = 30
      } 
     Division = 
     {  id       = {  type = 12700 id = 1501  } 
       name     = "49th (West Riding) Division" 
       type     = infantry 
	   model    = 11
       strength = 100
       experience = 40
      } 
    } 
   landunit = 
   {  name     = "XII Corps" 
     location = 29 
     id       = {  type = 12700 id = 3813  } 
     Division = 
     {  id       = {  type = 12700 id = 7  } 
       name     = "3rd Infantry Division" 
       type     = motorized 
       strength = 90
	   model    = 2
       extra    = sp_artillery
       brigade_model = 0
       experience = 40
      } 
     Division = 
     {  id       = {  type = 12700 id = 513  } 
       name     = "15th (Scottish) Division" 
       type     = infantry 
	   model    = 11
       strength = 85
       experience = 30
      }  
     Division = 
     {  id       = {  type = 12700 id = 512  } 
       name     = "51st (Highland) Division" 
       type     = infantry 
	   model    = 11
       strength = 85
       extra    = sp_artillery
       brigade_model = 0
       experience = 40
      }  
     Division = 
     {  id       = {  type = 12700 id = 511  } 
       name     = "52nd (Lowland) Division" 
       type     = infantry 
	   model    = 11
	   extra = amph_armor
	   brigade_model = 0			
       strength = 80
       experience = 30 
      }  
     Division = 
     {  id       = {  type = 12700 id = 1900  } 
       name     = "7th Armoured Division" 
       type     = armor
	   model    = 2
       strength = 75
       experience = 40
      } 
     Division = 
     {  id       = {  type = 12700 id = 1508  } 
       name     = "79th Armoured Division" 
       type     = armor 
	   model    = 1
       strength = 60
       extra    = armored_car
       brigade_model = 5
       experience = 30 
      } 
    } 
   landunit = 
   {  name     = "XXX Corps" 
     location = 28 
     id       = {  type = 12700 id = 3814  } 
     Division = 
     {  id       = {  type = 12700 id = 505  } 
       name     = "43rd (Wessex) Division" 
       type     = infantry 
	   model    = 11
       strength = 85
       experience = 40
      }    
     Division = 
     {  id       = {  type = 12700 id = 516  } 
       name     = "53rd (Welsh) Division" 
       type     = infantry 
	   model    = 11
       strength = 85
       experience = 30 
      }  
     Division = 
     {  id       = {  type = 12700 id = 1941  } 
       name     = "Guards Armoured Division" 
       type     = armor 
	   model    = 2
       strength = 80
       experience = 30 
      }   
     Division = 
     {  id       = {  type = 12700 id = 1925  } 
       name     = "11th Armoured Division" 
       type     = armor 
	   model    = 2
       strength = 55
       experience = 20
      } 
    } 
   landunit = 
   {  name     = "8th Army" 
      leader   = 10178 # McCreery
     location = 28 
     id       = {  type = 12700 id = 1930  } 
     Division = 
     {  id       = {  type = 12700 id = 1931  } 
       name     = "8th Army" 
       type     = hq 
       model    = 4 
       strength = 70
       extra    = anti_air
       brigade_model = 4
       experience = 40
      }
     Division = 
     {  id       = {  type = 12700 id = 5  } 
       name     = "5th Infantry Division" 
       type     = motorized 
	   model    = 2
       strength = 100
       experience = 40
      }
    } 
   landunit = 
   {  name     = "V Corps" 
     location = 28 
     id       = {  type = 12700 id = 3816  } 
     Division = 
     {  id            = {  type = 12700 id = 2  } 
       name 	= "1st Infantry Division" 
       type 	= motorized
	   model 	= 2
       strength = 100
	   extra 	= light_armor_brigade
	   brigade_model = 3
       experience = 30
      } 
     Division = 
     {  id       = {  type = 12700 id = 529  } 
       name     = "56th (London) Division" 
       type     = motorized 
	   model    = 2
       strength = 80
       extra    = anti_air
       brigade_model = 4
       experience = 30 
      }  
     Division = 
     {  id       = {  type = 12700 id = 1505  } 
       name     = "78th Division" 
       type     = infantry 
	   model    = 11
       strength = 80
       experience = 40
      }  
    } 
   landunit = 
   {  name     = "2 Korpus Wojska Polskiego" 
     location = 28 
     id       = {  type = 12700 id = 3807  } 
     Division = 
     {  id       = {  type = 12700 id = 3808  } 
       name     = "3 Dywizja Strzelców Karpackich" 
       type     = infantry 
	   model    = 11
       strength = 80
       experience = 30
      }  
     Division = 
     {  id       = {  type = 12700 id = 3809  } 
       name     = "5 Kresowa Dywizja Piechoty" 
       type     = infantry 
	   model    = 11
       strength = 80
       experience = 30
      }  
     Division = 
     {  id       = {  type = 12700 id = 3810  } 
       name     = "7 Dywizja Piechoty" 
       type     = infantry 
	   model    = 11
       strength = 80
       experience = 30
      }  
     Division = 
     {  id       = {  type = 12700 id = 3815  } 
       name     = "2 Warszawska Dywizja Pancerna" 
       type     = light_armor 
	   model    = 2
       strength = 40
      }  
    } 
   landunit = 
   {  name     = "1 Dywizja Pancerna" 
     location = 29 
     id       = {  type = 12700 id = 3811  } 
     Division = 
     {  id       = {  type = 12700 id = 3812  } 
       name     = "1 Dywizja Pancerna" 
       type     = armor 
	   model    = 1
       strength = 60
      }  
    } 
   landunit = 
   {  name     = "III Corps" 
     location = 28 
     id       = {  type = 12700 id = 1935  } 
     Division = 
     {  id       = {  type = 12700 id = 522  } 
       name     = "4th Infantry Division" 
       type     = motorized 
       strength = 100
	   model    = 2
	   extra    = anti_air
       brigade_model = 4
       experience = 30
      } 
     Division = 
     {  id       = {  type = 12700 id = 1504  } 
       name     = "46th (West Riding) Division" 
       type     = infantry 
	   model    = 11
       strength = 100
       experience = 30 
      }   
    } 
   landunit = 
   {  name     = "81st Division" 
     location = 1450 
     id       = {  type = 12700 id = 282  } 
     Division = 
     {  id       = {  type = 12700 id = 3801  } 
       name     = "81st (West Africa) Division" 
       type     = infantry 
	   model    = 11
       strength = 80
      } 
    } 
   landunit = 
   {  name     = "82nd Division" 
     location = 1511 
     id       = {  type = 12700 id = 283  } 
     Division = 
     {  id       = {  type = 12700 id = 3802  } 
       name     = "82nd (West Africa) Division" 
       type     = infantry 
	   model    = 11
       strength = 80
      } 
    } 
   landunit = 
   {  name     = "British Troops on Gibraltar" 
     location = 348 
     id       = {  type = 12700 id = 12  } 
     Division = 
     {  id       = {  type = 12700 id = 13  } 
       name     = "Gibraltar Defence Force" 
       type     = garrison 
	   model    = 5
       strength = 25
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "Ceylon Command" 
     location = 1511 
     id       = {  type = 12700 id = 14  } 
     Division = 
     {  id       = {  type = 12700 id = 15  } 
       name     = "Ceylon Defence Force" 
       type     = militia 
	   model    = 5
       strength = 80
      } 
    } 
   landunit = 
   {  name     = "Malta Command" 
     location = 429 
     id       = {  type = 12700 id = 16  } 
     Division = 
     {  id       = {  type = 12700 id = 17  } 
       name     = "Malta Defence Force" 
       type     = garrison 
	   model    = 5
       strength = 35
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "14th Army" 
      #leader   = ##### # Slim
     location = 1441 
     id       = {  type = 12700 id = 1938  } 
     Division = 
     {  id       = {  type = 12700 id = 1939  } 
       name     = "14th Army" 
       type     = hq 
       model    = 4 
       strength = 80
       extra    = anti_air
       brigade_model = 4
       experience = 30 
      }
     Division = 
     {  id       = {  type = 12700 id = 4800  } 
       name     = "11th (East Africa) Division" 
       type     = infantry 
	   model    = 11
       strength = 100
      } 
    } 
   landunit = 
   {  name     = "2nd Division" 
     location = 1442 
     id       = {  type = 12700 id = 1901  } 
     Division = 
     {  id       = {  type = 12700 id = 3  } 
       name     = "2nd Infantry Division" 
       type     = infantry
		model   = 11	   
       strength = 80
	   extra    = light_armor_brigade
	   brigade_model = 2
       experience = 30 
      } 
    } 
   landunit = 
   {  name     = "70th Division" 
     location = 1450 
     id       = {  type = 12700 id = 1940  } 
     Division = 
     {  id       = {  type = 12700 id = 19  } 
       name     = "70th Division" 
       type     = infantry 
	   model    = 11
       strength = 40
       experience = 30 
      } 
    }
   landunit = 
   {  name     = "9th Army" 
      #leader   = ##### # Holmes
     location = 1172 
     id       = {  type = 12700 id = 1936  } 
     Division = 
     {  id       = {  type = 12700 id = 1937  } 
       name     = "9th Army" 
       type     = hq 
       model    = 4 
       strength = 80
       extra    = anti_air
       brigade_model = 4
      }
     Division = 
     {  id       = {  type = 12700 id = 531  } 
       name     = "8th Infantry Division" 
       type     = infantry 
	   model    = 11
       strength = 20
      }
    }
 landunit = 
   {  name     = "Gold Coast Defence Force" 
     location = 956 
     id       = {  type = 12700 id = 43  } 
     Division = 
     {  id       = {  type = 12700 id = 44  } 
       name     = "The Gold Coast Regiment" 
       type     = militia 
	   model    = 5
       strength = 30
      } 
    } 
   landunit = 
   {  name     = "British troops in the Sudan" 
     location = 810 
     id       = {  type = 12700 id = 45  } 
     Division = 
     {  id       = {  type = 12700 id = 46  } 
       name     = "Sudan Defence Force" 
       type     = militia 
	   model    = 5
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Southern Rhodesia Defence Force" 
     location = 867 
     id       = {  type = 12700 id = 47  } 
     Division = 
     {  id       = {  type = 12700 id = 48  } 
       name     = "Southern Rhodesia Defence Force" 
       type     = militia 
	   model    = 5
       strength = 30
      } 
    } 
   landunit = 
   {  name     = "East Africa Force" 
     location = 841 
     id       = {  type = 12700 id = 55  } 
     Division = 
     {  id       = {  type = 12700 id = 56  } 
       name     = "King's African Rifles" 
       type     = militia 
	   model    = 5
       strength = 70
      } 
    }
   # ################# 
   # Royal Navy # 
   # ################# 

	# HOME FLEET
	navalunit = { 
		id = { type = 12700 id = 84 } 
		name = "Home Fleet" 
		location = 5 
		base = 5  
		division = { 
			id = { type = 12700 id = 93 } 
			name = "HMS Furious" 
			type = carrier 
			extra1 = cag 
			brigade_model1 = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 208 } 
			name = "HMS Berwick" 
			type = heavy_cruiser 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			}
		division = { 
			id = { type = 12700 id = 212 } 
			name = "HMS Kent" 
			type = heavy_cruiser 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			} 
		division = { 
			id = { type = 12700 id = 156 } 
			name = "HMS Devonshire" 
			type = heavy_cruiser 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			} 
		division = { 
			id = { type = 12700 id = 274 } 
			name = "HMS Jamaica" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 234 } 
			name = "HMS Sheffield" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 101 } 
			name = "Destroyer Division 1" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 102 } 
			name = "Destroyer Division 2" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 103 } 
			name = "Destroyer Division 3" 
			type = destroyer 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 95 } 
			name = "Destroyer Division 4" 
			type = destroyer 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 131 } 
			name = "Destroyer Division 5" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		}
	# Reserve Fleet
	navalunit = { 
		id = { type = 12700 id = 202 } 
		name = "Reserve Fleet" 
		location = 36 
		base = 36  
		division = { 
			id = { type = 12700 id = 295 } 
			name = "HMS Colossus" 
			type = escort_carrier 
                        model = 4
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 150 } 
			name = "HMS Valiant" 
			type = battleship 
			model = 4 
			experience = 30 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = floatplane
			brigade_model3 = 6
			}
		division = { 
			id = { type = 12700 id = 89 } 
			name = "HMS Resolution" 
			type = battleship 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			} 
		division = { 
			id = { type = 12700 id = 188 } 
			name = "HMS Norfolk" 
			type = heavy_cruiser 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			}
		division = { 
			id = { type = 12700 id = 218 } 
			name = "HMS Cardiff" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 196 } 
			name = "HMS Capetown" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			}  
		division = { 
			id = { type = 12700 id = 222 } 
			name = "HMS Dauntless" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 184 } 
			name = "HMS Carlisle" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 189 } 
			name = "HMS Diomede" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			}  
		division = { 
			id = { type = 12700 id = 2161 } 
			name = "HMS Liverpool" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 230 } 
			name = "HMS Birmingham" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 264 } 
			name = "HMS Cleopatra" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 267 } 
			name = "HMS Bellona" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 132 } 
			name = "Destroyer Division 6" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 133 } 
			name = "Destroyer Division 7" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		}
	# MEDITERRANEAN FLEET
	navalunit = { 
		id = { type = 12700 id = 147 } 
		name = "Mediterranean Fleet" 
		location = 789 
		base = 789
		division = { 
			id = { type = 12700 id = 2200 } 
			name = "HMS Dido" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 1670 } 
			name = "HMS Phoebe" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 270 } 
			name = "HMS Royalist" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 135 } 
			name = "Destroyer Division 8" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 136 } 
			name = "Destroyer Division 9" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 138 } 
			name = "Destroyer Division 10" 
			type = destroyer 
			model = 6 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 139 } 
			name = "Destroyer Division 11" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 141 } 
			name = "Destroyer Division 12" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 142 } 
			name = "Destroyer Division 13" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 144 } 
			name = "Destroyer Division 14" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		}
	# FORCE A
	navalunit = { 
		id = { type = 12700 id = 1470 } 
		name = "Force A" 
		location = 27 
		base = 27
		division = { 
			id = { type = 12700 id = 2020 } 
			name = "HMS Albatross" 
			type = escort_carrier 
			model = 0 
			}
		division = { 
			id = { type = 12700 id = 152 } 
			name = "HMS Warspite" 
			type = battleship 
			model = 4 
			experience = 30 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = floatplane
			brigade_model3 = 6
			} 
		division = { 
			id = { type = 12700 id = 90 } 
			name = "HMS Ramillies" 
			type = battleship 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			} 
		division = { 
			id = { type = 12700 id = 86 } 
			name = "HMS Rodney" 
			type = battleship 
			model = 6 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			}  
		division = { 
			id = { type = 12700 id = 85 } 
			name = "HMS Nelson" 
			type = battleship 
			model = 6 
			experience = 30
			extra1 = naval_anti_air_l
			extra2 = floatplane
			brigade_model2 = 6
			}
		division = { 
			id = { type = 12700 id = 3900 } 
			name = "HMS Roberts" 
			type = heavy_cruiser # Roberts-class monitor
			model = 4 
			experience = 30 
			extra1 = naval_fire_controll_l
			brigade_model1 = 0
			} 
		division = { 
			id = { type = 12700 id = 1807 } 
			name = "HMS Erebus" 
			type = heavy_cruiser # Erebus-class monitor
			model = 2 
			experience = 30 
			extra1 = naval_fire_controll_l
			brigade_model1 = 0
			} 
		division = { 
			id = { type = 12700 id = 221 } 
			name = "HMS Danae" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 205 } 
			name = "HMS Frobisher" 
			type = heavy_cruiser 
			model = 2 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			} 
		division = { 
			id = { type = 12700 id = 207 } 
			name = "HMS Hawkins" 
			type = heavy_cruiser 
			model = 2 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			} 
		division = { 
			id = { type = 12700 id = 167 } 
			name = "HMS Arethusa" 
			type = light_cruiser 
			model = 4 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 190 } 
			name = "HMS Emerald" 
			type = light_cruiser 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 191 } 
			name = "HMS Enterprise" 
			type = light_cruiser 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 165 } 
			name = "HMS Despatch" 
			type = light_cruiser 
			model = 2
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 178 } 
			name = "ORP Dragon" 
			type = light_cruiser 
			model = 2
			experience = 30 
                        extra1 = naval_improved_hull_s
			}
		division = { 
			id = { type = 12700 id = 179 } 
			name = "HMS Ajax" 
			type = light_cruiser 
			model = 4 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 100 } 
			name = "HMS Orion" 
			type = light_cruiser 
			model = 4 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 231 } 
			name = "HMS Glasgow" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 265 } 
			name = "HMS Scylla" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 262 } 
			name = "HMS Sirius" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 2168 } 
			name = "HMS Mauritius" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 219 } 
			name = "HMS Ceres" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			extra1 = naval_anti_air_s
			} 
		division = { 
			id = { type = 12700 id = 269 } 
			name = "HMS Diadem" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		} 
	# 1ST ESCORT GROUP
	navalunit = { 
		id = { type = 12700 id = 1450 } 
		name = "1st Escort Group" 
		location = 17 
		base = 17
		division = { 
			id = { type = 12700 id = 145 } 
			name = "Destroyer Division 15" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 146 } 
			name = "Destroyer Division 16" 
			type = destroyer 
			model = 6 
			experience = 30 
			} 
		} 
	# 1ST DESTROYER SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1451 } 
		name = "1st Destroyer Squadron" 
		location = 23 
		base = 23
		division = { 
			id = { type = 12700 id = 1452 } 
			name = "Destroyer Division 15" 
			type = destroyer 
			model = 6 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 1453 } 
			name = "Destroyer Division 16" 
			type = destroyer 
			model = 6 
			experience = 30 
			} 
		} 
	# 2ND ESCORT GROUP
	navalunit = { 
		id = { type = 12700 id = 1454 } 
		name = "2nd Escort Group" 
		location = 27 
		base = 27
		division = { 
			id = { type = 12700 id = 217 } 
			name = "HMS Colombo" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			extra1 = naval_anti_air_s
			}
		division = { 
			id = { type = 12700 id = 1455 } 
			name = "Destroyer Division 19" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 171 } 
			name = "Destroyer Division 20" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		} 
	# ROSYTH ESCORT FORCE
	navalunit = { 
		id = { type = 12700 id = 1456 } 
		name = "Rosyth Escort Force" 
		location = 13 
		base = 13
		division = { 
			id = { type = 12700 id = 172 } 
			name = "Destroyer Division 21" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		} 
	# 2ND DESTROYER SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1457 } 
		name = "2nd Destroyer Squadron" 
		location = 23 
		base = 23
		division = { 
			id = { type = 12700 id = 173 } 
			name = "Destroyer Division 22" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 180 } 
			name = "Destroyer Division 23" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 181 } 
			name = "Destroyer Division 24" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		} 
	# 3RD DESTROYER SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1459 } 
		name = "3rd Destroyer Squadron" 
		location = 23 
		base = 23
		division = { 
			id = { type = 12700 id = 185 } 
			name = "Destroyer Division 25" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 186 } 
			name = "Destroyer Division 26" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		} 
	# 3RD ESCORT GROUP
	navalunit = { 
		id = { type = 12700 id = 1460 } 
		name = "3rd Escort Group" 
		location = 36 
		base = 36
		division = { 
			id = { type = 12700 id = 192 } 
			name = "Destroyer Division 27" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		} 
	# EAST INDIES FORCE
	navalunit = { 
		id = { type = 12700 id = 2411 } 
		name = "East Indies Force" 
		location = 1511 
		base = 1511
		division = { 
			id = { type = 12700 id = 9601 } 
			name = "HMS Nigeria" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}  
		division = { 
			id = { type = 12700 id = 278 } 
			name = "HMS Ceylon" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 193 } 
			name = "Destroyer Division 28" 
			type = destroyer 
			model = 6 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 1830 } 
			name = "Destroyer Division 29" 
			type = destroyer 
			model = 6 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 1831 } 
			name = "Destroyer Division 30" 
			type = destroyer 
			model = 6 
			experience = 30 
			} 
		}
	# EASTERN FLEET
	navalunit = { 
		id = { type = 12700 id = 1474 } 
		name = "Eastern Fleet" 
		location = 1511 
		base = 1511
		division = { 
			id = { type = 12700 id = 148 } 
			name = "HMS Queen Elizabeth" 
			type = battleship 
			model = 4 
			experience = 30 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = floatplane
			brigade_model3 = 6
			}
		division = { 
			id = { type = 12700 id = 92 } 
			name = "HMS Renown" 
			type = battlecruiser 
			model = 1 
			experience = 30 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = naval_improved_hull_l
			extra4 = floatplane
			brigade_model4 = 6
			} 
		division = { 
			id = { type = 12700 id = 159 } 
			name = "HMS Sussex" 
			type = heavy_cruiser 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 5
			} 
		division = { 
			id = { type = 12700 id = 157 } 
			name = "HMS London" 
			type = heavy_cruiser 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			extra2 = naval_anti_air_l
			extra3 = naval_improved_hull_l
			extra4 = naval_radar_l
			brigade_model4 = 2
			} 
		division = { 
			id = { type = 12700 id = 273 } 
			name = "HMS Gambia" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 210 } 
			name = "HMS Cumberland" 
			type = heavy_cruiser 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			}   
		division = { 
			id = { type = 12700 id = 211 } 
			name = "HMS Suffolk" 
			type = heavy_cruiser 
			model = 3 
			experience = 30 
			extra1 = floatplane
			brigade_model1 = 6
			} 
		division = { 
			id = { type = 12700 id = 232 } 
			name = "HMS Newcastle" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 9600 } 
			name = "HMS Kenya" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}  
		division = { 
			id = { type = 12700 id = 215 } 
			name = "HMS Caradoc" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			} 
		}
	# FORCE H
	navalunit = { 
		id = { type = 12700 id = 1471 } 
		name = "Force H" 
		location = 348 
		base = 348
		division = { 
			id = { type = 12700 id = 164 } 
			name = "HMS Delhi" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 213 } 
			name = "HMS Caledon" 
			type = light_cruiser 
			model = 2 
			experience = 30 
			extra1 = naval_anti_air_s
			} 
		division = { 
			id = { type = 12700 id = 229 } 
			name = "HMS Aurora" 
			type = light_cruiser 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 224 } 
			name = "Destroyer Division 31" 
			type = destroyer 
			model = 5 
			experience = 30 
			} 
		} 
	# PACIFIC FLEET
	navalunit = { 
		id = { type = 12700 id = 2423 } 
		name = "Pacific Fleet" 
		location = 1511 
		base = 1511
		division = { 
			id = { type = 12700 id = 2362 } 
			name = "HMS Illustrious" 
			type = carrier 
                        model = 3
			extra1 = cag 
			brigade_model1 = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 246 } 
			name = "HMS Indefatigable" 
			type = carrier 
                        model = 4
			extra1 = cag 
			brigade_model1 = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2361 } 
			name = "HMS Formidable" 
			type = carrier 
                        model = 3
			extra1 = cag 
			brigade_model1 = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 245 } 
			name = "HMS Implacable" 
			type = carrier 
                        model = 4
			extra1 = cag 
			brigade_model1 = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2360 } 
			name = "HMS Victorious" 
			type = carrier 
                        model = 3
			extra1 = cag 
			brigade_model1 = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 244 } 
			name = "HMS Indomitable" 
			type = carrier 
                        model = 3
			extra1 = cag 
			brigade_model1 = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 243 } 
			name = "HMS Unicorn" 
			type = escort_carrier 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 242 } 
			name = "HMS Howe" 
			type = battleship 
			model = 7 
			experience = 30 
			extra1 = naval_anti_air_l
			extra2 = naval_radar_l
			brigade_model2 = 2
			extra3 = floatplane
			brigade_model3 = 6   
			}  
		division = { 
			id = { type = 12700 id = 8600 } 
			name = "HMS King George V" 
			type = battleship 
			model = 7 
			experience = 30 
			extra1 = naval_anti_air_l
			extra2 = naval_radar_l
			brigade_model2 = 2
			extra3 = floatplane
			brigade_model3 = 6
			}  
		division = { 
			id = { type = 12700 id = 266 } 
			name = "HMS Argonaut" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 268 } 
			name = "HMS Black Prince" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 2166 } 
			name = "HMS Belfast" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 272 } 
			name = "HMS Bermuda" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 261 } 
			name = "HMS Euryalus" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 279 } 
			name = "HMS Newfoundland" 
			type = light_cruiser 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 281 } 
			name = "HMS Swiftsure" 
			type = light_cruiser 
                        model = 6
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 225 } 
			name = "Destroyer Division 32" 
			type = destroyer 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 226 } 
			name = "Destroyer Division 33" 
			type = destroyer 
			model = 6 
			experience = 30 
			} 
		} 
	# 1ST SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 174 } 
		name = "1st Submarine Squadron" 
		location = 13 
		base = 13 
		division = { 
			id = { type = 12700 id = 175 } 
			name = "1st Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 176 } 
			name = "2nd Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 30 
			} 
		} 
	# 3RD SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 199 } 
		name = "3rd Submarine Squadron" 
		location = 36 
		base = 36 
		division = { 
			id = { type = 12700 id = 107 } 
			name = "3rd Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 108 } 
			name = "4th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 109 } 
			name = "5th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 110 } 
			name = "6th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 111 } 
			name = "7th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 30 
			}  
		} 
	# 4TH SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1990 } 
		name = "4th Submarine Squadron" 
		location = 1511 
		base = 1511 
		division = { 
			id = { type = 12700 id = 200 } 
			name = "8th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 201 } 
			name = "9th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 228 } 
			name = "10th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 30 
			} 
		} 
	# 5TH SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1991 } 
		name = "5th Submarine Squadron" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 2280 } 
			name = "11th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2281 } 
			name = "12th Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 1462 } 
			name = "13th Submarine Flotilla" 
			type = submarine 
			model = 6 
			experience = 30 
			} 
		} 
	# 6TH SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 1463 } 
		name = "6th Submarine Squadron" 
		location = 13 
		base = 13 
		division = { 
			id = { type = 12700 id = 1464 } 
			name = "14th Submarine Flotilla" 
			type = submarine 
			model = 6 
			experience = 30 
			} 
		} 
	# 7TH SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4000 } 
		name = "7th Submarine Squadron" 
		location = 36 
		base = 36 
		division = { 
			id = { type = 12700 id = 4001 } 
			name = "15th Submarine Flotilla" 
			type = submarine 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4002 } 
			name = "16th Submarine Flotilla" 
			type = submarine 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4003 } 
			name = "17th Submarine Flotilla" 
			type = submarine 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4004 } 
			name = "18th Submarine Flotilla" 
			type = submarine 
			model = 5 
			experience = 30 
			} 
		} 
	# 8TH SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4005 } 
		name = "8th Submarine Squadron" 
		location = 1511 
		base = 1511 
		division = { 
			id = { type = 12700 id = 4006 } 
			name = "19th Submarine Flotilla" 
			type = submarine 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4007 } 
			name = "20th Submarine Flotilla" 
			type = submarine 
			model = 6 
			experience = 30 
			} 
		} 
	# 9TH SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4008 } 
		name = "9th Submarine Squadron" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 4009 } 
			name = "21st Submarine Flotilla" 
			type = submarine 
			model = 5 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4010 } 
			name = "22nd Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 30 
			} 
		} 
	# 10TH SUBMARINE SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4011 } 
		name = "10th Submarine Squadron" 
		location = 430 
		base = 430 
		division = { 
			id = { type = 12700 id = 4012 } 
			name = "23rd Submarine Flotilla" 
			type = submarine 
			model = 5 
			experience = 30 
			} 
		} 
	# 1ST TRANSPORT SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4013 } 
		name = "1st Transport Squadron" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 113 } 
			name = "1st Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 114 } 
			name = "2nd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2500 } 
			name = "3rd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4014 } 
			name = "4th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4015 } 
			name = "5th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 116 } 
			name = "6th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 117 } 
			name = "7th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 122 } 
			name = "8th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			}  
		division = { 
			id = { type = 12700 id = 119 } 
			name = "9th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		} 
	# 2ND TRANSPORT SQUADRON
	navalunit = { 
		id = { type = 12700 id = 2022 } 
		name = "2nd Transport Squadron" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 120 } 
			name = "10th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 121 } 
			name = "11th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2503 } 
			name = "12th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 124 } 
			name = "13th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 125 } 
			name = "14th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			}  
		division = { 
			id = { type = 12700 id = 2504 } 
			name = "15th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2505 } 
			name = "16th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 127 } 
			name = "17th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 128 } 
			name = "18th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 129 } 
			name = "19th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		} 
	# 3RD TRANSPORT SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4016 } 
		name = "3rd Transport Squadron" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 2506 } 
			name = "20th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2508 } 
			name = "21st Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2509 } 
			name = "22nd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2510 } 
			name = "23rd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2511 } 
			name = "24th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2512 } 
			name = "25th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2513 } 
			name = "26th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2514 } 
			name = "27th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2515 } 
			name = "28th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2516 } 
			name = "29th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		} 
	# 4TH TRANSPORT SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4017 } 
		name = "4th Transport Squadron" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 1812 } 
			name = "30th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2518 } 
			name = "31st Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2519 } 
			name = "32nd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2520 } 
			name = "33rd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2521 } 
			name = "34th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2522 } 
			name = "35th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2507 } 
			name = "36th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			}
		division = { 
			id = { type = 12700 id = 2523 } 
			name = "37th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2524 } 
			name = "38th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 2525 } 
			name = "39th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		} 
	# 5TH TRANSPORT SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4018 } 
		name = "5th Transport Squadron" 
		location = 789 
		base = 789 
		division = { 
			id = { type = 12700 id = 4019 } 
			name = "40th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4020 } 
			name = "41st Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4021 } 
			name = "42nd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4022 } 
			name = "43rd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4023 } 
			name = "44th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4024 } 
			name = "45th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4025 } 
			name = "46th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4026 } 
			name = "47th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4027 } 
			name = "48th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4028 } 
			name = "49th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		} 
	# 6TH TRANSPORT SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4029 } 
		name = "6th Transport Squadron" 
		location = 789 
		base = 789 
		division = { 
			id = { type = 12700 id = 4030 } 
			name = "50th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4031 } 
			name = "51st Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4032 } 
			name = "52nd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4033 } 
			name = "53rd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4034 } 
			name = "54th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4035 } 
			name = "55th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4036 } 
			name = "56th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4037 } 
			name = "57th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4038 } 
			name = "58th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4039 } 
			name = "59th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		} 
	# 7TH TRANSPORT SQUADRON
	navalunit = { 
		id = { type = 12700 id = 4040 } 
		name = "7th Transport Squadron" 
		location = 1511 
		base = 1511 
		division = { 
			id = { type = 12700 id = 4041 } 
			name = "60th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4042 } 
			name = "61st Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4043 } 
			name = "62nd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4044 } 
			name = "63rd Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4045 } 
			name = "64th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4046 } 
			name = "65th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4047 } 
			name = "66th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4048 } 
			name = "67th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4049 } 
			name = "68th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		division = { 
			id = { type = 12700 id = 4050 } 
			name = "69th Transport Flotilla" 
			type = transport 
			model = 3 
			experience = 30 
			} 
		} 
   # ################# 
   # Royal Airforce # 
   # ################# 
  airunit = 
  { location = 19 
    base     = 19 
    id       = {  type = 12700 id = 7900  } 
    name     = "No.10 Group" 
    division =
    { experience = 30
      id       = {  type = 12700 id = 7901  } 
      name     = "No.126 Squadron" 
      type     = multi_role 
      model    = 7
      strength = 100
    } 
    division =
    { experience = 30
      id       = {  type = 12700 id = 7902  } 
      name     = "No.165 Squadron" 
      type     = multi_role 
      model    = 7
      strength = 100
    } 
    division =
    { experience = 30
      id       = {  type = 12700 id = 7903  } 
      name     = "No.406 Squadron RCAF" 
      type     = tactical_bomber 
      model    = 8 
      strength = 100
    } 
    division =
    { experience = 30
      id       = {  type = 12700 id = 7904  } 
      name     = "No.464 Squadron RCAF" 
      type     = tactical_bomber 
      model    = 8 
      strength = 100
    } 
    division =
    { experience = 30
      id       = {  type = 12700 id = 7905  } 
      name     = "No.610 Squadron" 
      type     = multi_role 
      model    = 6
      strength = 100
    } 
  } 
  airunit =
  { location = 26
    base     = 26
    id       = { type = 10499 id = 7906 }
    name     = "No.11 Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 7907 }
      name       = "No.1 Squadron"
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7908 }
      name       = "No.64 Squadron"
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7909 }
      name       = "No.313 Squadron "
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7910 }
      name       = "No.501 Squadron "
      strength   = 100
      type       = multi_role
      model      = 6
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7911 }
      name       = "No.219 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 8
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7912 }
      name       = "No.29 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7913 }
      name       = "No.303 Squadron"
      strength   = 100
      type       = multi_role
      model      = 6
    }
  }
  airunit =
  { location = 27
    base     = 27
    id       = { type = 10499 id = 7914 }
    name     = "2nd TAF/1"
    division =
    { experience = 30
      id         = { type = 10499 id = 7915 }
      name       = "No.3 Squadron"
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7916 }
      name       = "No.33 Squadron"
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7917 }
      name       = "No.137 Squadron"
      strength   = 100
      type       = interceptor
      model      = 9
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7918 }
      name       = "No.184 Squadron"
      strength   = 100
      type       = interceptor
      model      = 10
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7919 }
      name       = "No.245 Squadron"
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7920 }
      name       = "No.264 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 8
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7921 }
      name       = "No.416 Squadron RCAF"
      strength   = 100
      type       = interceptor
      model      = 10
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7922 }
      name       = "No.80 Squadron"
      strength   = 100
      type       = interceptor
      model      = 10
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7923 }
      name       = "No.132 Squadron "
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7924 }
      name       = "No.183 Squadron"
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7925 }
      name       = "No.308 Squadron "
      strength   = 100
      type       = interceptor
      model      = 10
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7926 }
      name       = "No.331 Squadron "
      strength   = 100
      type       = interceptor
      model      = 10
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7927 }
      name       = "No.332 Squadron "
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7928 }
      name       = "No.694 Squadron"
      strength   = 100
      type       = multi_role
      model      = 6
    }
  }
  airunit =
  { location = 26
    base     = 26
    id       = { type = 10499 id = 7929 }
    name     = "2nd TAF/2"
    division =
    { experience = 30
      id         = { type = 10499 id = 7930 }
      name       = "No.65 Squadron"
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7931 }
      name       = "No.181 Squadron"
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7932 }
      name       = "No.401 Squadron RCAF "
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7933 }
      name       = "No.412 Squadron RCAF "
      strength   = 100
      type       = interceptor
      model      = 10
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7934 }
      name       = "No.441 Squadron RCAF "
      strength   = 100
      type       = interceptor
      model      = 10
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 10499 id = 7935 }
    name     = "No.12 Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 7936 }
      name       = "No.168 Squadron"
      strength   = 75
      type       = multi_role
      model      = 6
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7937 }
      name       = "No.25 Squadron"
      strength   = 75
      type       = tactical_bomber
      model      = 7
    }
  }
  airunit =
  { location = 26
    base     = 26
    id       = { type = 10499 id = 7938 }
    name     = "No.13 Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 7939 }
      name       = "No.504 Squadron"
      strength   = 100
      type       = interceptor
      model      = 10
    }
  }
  airunit =
  { location = 26
    base     = 26
    id       = { type = 10499 id = 7940 }
    name     = "No.14 Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 7941 }
      name       = "No.118 Squadron"
      strength   = 100
      type       = interceptor
      model      = 9
    }
  }
  airunit =
  { location = 10
    base     = 10
    id       = { type = 10499 id = 7942 }
    name     = "No.38 Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 7943 }
      name       = "No.190 Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7944 }
      name       = "No.297 Squadron "
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7945 }
      name       = "No.570 Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
  }
  airunit =
  { location = 13
    base     = 13
    id       = { type = 10499 id = 7946 }
    name     = "No.603 Squadron"
    division =
    { experience = 30
      id         = { type = 10499 id = 7947 }
      name       = "No.603 Squadron "
      strength   = 100
      type       = interceptor
      model      = 8
    }
  }
  airunit =
  { location = 348
    base     = 348
    id       = { type = 10499 id = 7948 }
    name     = "No.43 Squadron"
    division =
    { experience = 30
      id         = { type = 10499 id = 7949 }
      name       = "No.43 Squadron"
      strength   = 100
      type       = interceptor
      model      = 8
    }
  }
  airunit =
  { location = 1447
    base     = 1447
    id       = { type = 10499 id = 7950 }
    name     = "1/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 7951 }
      name       = "17./67./81. Squadron"
      strength   = 100
      type       = multi_role
      model      = 6
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7952 }
      name       = "136./155. Squadron"
      strength   = 100
      type       = multi_role
      model      = 6
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7953 }
      name       = "607./615. Squadron"
      strength   = 100
      type       = multi_role
      model      = 6
    }
  }
  airunit =
  { location = 1697
    base     = 1697
    id       = { type = 10499 id = 7954 }
    name     = "ANZAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 7955 }
      name       = "452./455./54. Squadron"
      strength   = 100
      type       = interceptor
      model      = 10
    }
  }
  airunit =
  { location = 1447
    base     = 1447
    id       = { type = 10499 id = 7956 }
    name     = "2/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 7957 }
      name       = "5./11./20. Squadron"
      strength   = 100
      type       = multi_role
      model      = 7
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7958 }
      name       = "28./30. Squadron"
      strength   = 100
      type       = multi_role
      model      = 6
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7959 }
      name       = "42./34./42. Squadron"
      strength   = 100
      type       = cas
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7960 }
      name       = "60./79. Squadron"
      strength   = 100
      type       = cas
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7961 }
      name       = "113./123./134. Squadron"
      strength   = 100
      type       = cas
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7962 }
      name       = "135./146./152. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7963 }
      name       = "258./261./273. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7964 }
      name       = "No.45 Squadron"
      strength   = 40
      type       = tactical_bomber
      model      = 8
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7965 }
      name       = "82./84./110. Squadron"
      strength   = 100
      type       = cas
      model      = 3
    }
  }
  airunit =
  { location = 1442
    base     = 1442
    id       = { type = 10499 id = 7966 }
    name     = "3/SEAC Air Forces"
    division =
    { experience    = 30
      id            = { type = 10499 id = 7967 }
      name          = "200./203./215. Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 7968 }
      name          = "99./159. Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 7969 }
      name          = "292./355./356. Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 1442
    base     = 1442
    id       = { type = 10499 id = 7970 }
    name     = "4/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 7971 }
      name       = "27./47./88. Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7972 }
      name       = "176./177./211. Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
  }
  airunit =
  { location = 1447
    base     = 1447
    id       = { type = 10499 id = 7973 }
    name     = "5/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 7974 }
      name       = "31./62./117. Squadron"
      strength   = 100
      type       = transport_plane
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7975 }
      name       = "194./435./436. Squadron"
      strength   = 100
      type       = transport_plane
      model      = 2
    }
  }
  airunit =
  { location = 23
    base     = 23
    id       = { type = 11128 id = 7976 }
    name     = "No.1 Group "
    division =
    { experience    = 30
      id            = { type = 11128 id = 7977 }
      name          = "No.12 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7978 }
      name          = "No.103 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7979 }
      name          = "No.300 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 4
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7980 }
      name          = "No.576 Squadron "
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7981 }
      name          = "No.625 Squadron "
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 11128 id = 7982 }
    name     = "No.3 Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 7983 }
      name          = "No.15 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 4
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7984 }
      name          = "No.115 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7985 }
      name          = "No.218 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 25
    base     = 25
    id       = { type = 11128 id = 7986 }
    name     = "No.4 Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 7987 }
      name          = "No.10 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7988 }
      name          = "No.76 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7989 }
      name          = "No.78 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 4
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7990 }
      name          = "No.346 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7991 }
      name          = "No.640 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 4
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 18
    base     = 18
    id       = { type = 11128 id = 7992 }
    name     = "No.5 Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 7993 }
      name          = "No.9 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7994 }
      name          = "No.49 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7995 }
      name          = "No.61 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7996 }
      name          = "No.106 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7997 }
      name          = "No.467 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 7998 }
      name          = "No.619 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 18
    base     = 18
    id       = { type = 11128 id = 7999 }
    name     = "No.6 Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 8000 }
      name          = "No.408 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 8001 }
      name          = "No.424 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 8002 }
      name          = "No.427 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 4
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 8003 }
      name          = "No.429 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 4
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 8004 }
      name          = "No.432 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 4
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 19
    base     = 19
    id       = { type = 11128 id = 8005 }
    name     = "No.8 Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 8006 }
      name          = "No.7 Squadron"
      strength      = 75
      type          = strategic_bomber
      model         = 4
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 8007 }
      name          = "No.156 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 8008 }
      name          = "No.582 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 5
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience = 30
      id         = { type = 11128 id = 8009 }
      name       = "No.692 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 7
    }
  }

   # Warships Under Construction# 
   division_development = 
   {  name  = "HMS Duke of York" # 1944-45 refit
     type  = battleship 
     model = 7
     cost  = 0.5
     unitcost = no
     id    = {  type = 12700 id = 240  } 
     date  = {  year = 1945 month = april day = 1  } 
     extra1 = naval_anti_air_l
     extra2 = naval_radar_l
     brigade_model2 = 2
     extra3 = floatplane
     brigade_model3 = 6   
    }
   division_development = 
   {  name  = "HMS Anson" # 1944-45 refit
     type  = battleship 
     model = 7
     cost  = 0.5
     unitcost = no
     id    = {  type = 12700 id = 241  } 
     date  = {  year = 1945 month = march day = 1  } 
     extra1 = naval_anti_air_l
     extra2 = naval_radar_l
     brigade_model2 = 2
     extra3 = floatplane
     brigade_model3 = 6   
    }
   division_development = 
   {  name  = "HMS Vanguard" 
     type  = battleship 
     model = 8
     cost  = 0.1
     id    = {  type = 12700 id = 297  } 
     date  = {  year = 1946 month = august day = 9  } 
     extra1 = floatplane
     brigade_model1 = 6   
    }
   division_development = 
   {  name  = "HMS Audacious" 
     type  = carrier 
     model = 5
     cost  = 0.1
     id    = {  type = 12700 id = 293  } 
     date  = {  year = 1946 month = march day = 19  } 
     extra = cag 
     brigade_model = 5  
    }
   division_development = 
   {  name  = "HMS Irresistible" 
     type  = carrier 
     model = 5
     cost  = 0.1
     id    = {  type = 12700 id = 304  } 
     date  = {  year = 1947 month = february day = 18  } 
     extra = cag 
     brigade_model = 5  
    }
   division_development = 
   {  name  = "HMS Glory" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 294  } 
     date  = {  year = 1945 month = april day = 2  } 
    }
   division_development = 
   {  name  = "HMS Ocean" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 296  } 
     date  = {  year = 1945 month = august day = 8  } 
    }
   division_development = 
   {  name  = "HMS Vengeance" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 292  } 
     date  = {  year = 1945 month = january day = 15  } 
    }
   division_development = 
   {  name  = "HMS Theseus" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 298  } 
     date  = {  year = 1946 month = february day = 9  } 
    }
   division_development = 
   {  name  = "HMS Triumph" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 299  } 
     date  = {  year = 1946 month = may day = 9  } 
    }
   division_development = 
   {  name  = "HMS Venerable" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 300  } 
     date  = {  year = 1945 month = january day = 17  } 
    }
   division_development = 
   {  name  = "HMS Warrior" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 301  } 
     date  = {  year = 1945 month = april day = 2  } 
    }
   division_development = 
   {  name  = "HMS Pioneer" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 302  } 
     date  = {  year = 1945 month = february day = 8  } 
    }
   division_development = 
   {  name  = "HMS Majestic" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 303  } 
     date  = {  year = 1946 month = august day = 1  } 
    }
   division_development = 
   {  name  = "HMS Terrible" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 305  } 
     date  = {  year = 1945 month = september day = 30  } 
    }
   division_development = 
   {  name  = "HMS Hercules" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 306  } 
     date  = {  year = 1946 month = september day = 22  } 
    }
   division_development = 
   {  name  = "HMS Magnificent" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 307  } 
     date  = {  year = 1945 month = november day = 16  } 
    }
   division_development = 
   {  name  = "HMS Leviathan" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 308  } 
     date  = {  year = 1946 month = june day = 7  } 
    }
   division_development = 
   {  name  = "HMS Powerful" 
     type  = escort_carrier 
     model = 4
     cost  = 0.1
     id    = {  type = 12700 id = 309  } 
     date  = {  year = 1946 month = february day = 27  } 
    }
   division_development = 
   {  name  = "HMS Centaur" 
     type  = escort_carrier 
     model = 5
     cost  = 0.1
     id    = {  type = 12700 id = 310  } 
     date  = {  year = 1947 month = april day = 22  } 
    }
   division_development = 
   {  name  = "HMS Albion" 
     type  = escort_carrier 
     model = 5
     cost  = 0.1
     id    = {  type = 12700 id = 311  } 
     date  = {  year = 1947 month = may day = 16  } 
    }
   division_development = 
   {  name  = "HMS Superb" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 291  } 
     date  = {  year = 1945 month = november day = 16  } 
    }
   division_development = 
   {  name  = "HMS Bellerophon" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 312  } 
     date  = {  year = 1945 month = october day = 25  } 
    }
   division_development = 
   {  name  = "HMS Defense" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 313  } 
     date  = {  year = 1945 month = september day = 2  } 
    }
   division_development = 
   {  name  = "HMS Tiger" 
     type  = light_cruiser 
     model = 6
     cost  = 0.1
     id    = {  type = 12700 id = 314  } 
     date  = {  year = 1945 month = december day = 20  } 
    }
  } 
 
